<?php if(!defined('ABSPATH'))exit;$msg=sanitize_key($_GET['sc_ei_msg']??'');
function sc_ei_analytics_rate($rate){return $rate['suppressed']?'Suppressed':($rate['percent']===null?'—':$rate['percent'].'%');}
function sc_ei_analytics_group($title,$rows){echo '<section class="sc-ei-admin__card"><h2>'.esc_html($title).'</h2><div class="sc-ei-analytics-bars">';if(!$rows)echo '<p>No data.</p>';foreach($rows as $r){$count=$r['suppressed']?'&lt; minimum':number_format_i18n($r['count']);echo '<div><span>'.esc_html(ucwords(str_replace(array('_','-'),' ',$r['label']))).'</span><strong>'.$count.'</strong></div>';}echo '</div></section>';}
?>
<div class="wrap sc-ei-admin sc-ei-analytics-admin"><header class="sc-ei-admin__header"><div><p class="sc-ei-admin__eyebrow">Aggregate Operational Intelligence</p><h1>Inquiry Analytics</h1><p>Understand demand, conversion, timing, workload, and bottlenecks without ranking senders or automating service decisions.</p></div><div class="sc-ei-admin__version">v0.12.0</div></header>
<?php if($msg):?><div class="notice notice-success"><p><?php echo esc_html(ucwords(str_replace('_',' ',$msg)));?></p></div><?php endif;?>
<div class="sc-ei-portal-admin-boundary"><strong>Privacy and decision boundary</strong><span>Aggregate counts only. Cohorts below <?php echo esc_html($analytics['minimum_cohort']);?> are suppressed. No names, emails, message bodies, document contents, sender scores, or automated fit and engagement decisions appear here.</span></div>
<form method="get" class="sc-ei-operation-filter-form"><input type="hidden" name="page" value="sc-engagement-intake-analytics"><select name="days"><?php foreach(SC_EI_Analytics_Schema::ranges() as $d=>$label):?><option value="<?php echo esc_attr($d);?>" <?php selected($analytics['range_days'],$d);?>><?php echo esc_html($label);?></option><?php endforeach;?></select><button class="button">Update range</button><?php if(current_user_can('sc_intake_export_analytics')):?><a class="button" href="<?php echo esc_url(wp_nonce_url(admin_url('admin-post.php?action=sc_ei_analytics_export&days='.$analytics['range_days']),'sc_ei_analytics_export_'.$analytics['range_days']));?>">Export aggregate JSON</a><?php endif;?></form>
<div class="sc-ei-review-metrics"><?php foreach($analytics['funnel'] as $k=>$v):?><a><strong><?php echo esc_html(number_format_i18n($v));?></strong><span><?php echo esc_html(ucwords(str_replace('_',' ',$k)));?></span></a><?php endforeach;?></div>
<section class="sc-ei-admin__card sc-ei-admin__card--wide"><h2>Conversion funnel</h2><table class="widefat striped"><thead><tr><th>Stage</th><th>Count</th><th>Rate</th><th>Evidence</th></tr></thead><tbody><?php foreach(array('review_start'=>'Review started','decision'=>'Decision recorded','meeting'=>'Meeting progressed','proposal'=>'Proposal published','contract'=>'Published proposal contracted','activation'=>'Contracted proposal activated') as $k=>$label):$r=$analytics['rates'][$k];?><tr><td><?php echo esc_html($label);?></td><td><?php echo $r['suppressed']?'Suppressed':esc_html(number_format_i18n($r['numerator']));?></td><td><?php echo esc_html(sc_ei_analytics_rate($r));?></td><td><?php echo esc_html($r['suppressed']?'Small denominator':$r['numerator'].' / '.$r['denominator']);?></td></tr><?php endforeach;?></tbody></table></section>
<div class="sc-ei-analytics-grid"><?php sc_ei_analytics_group('Source pages',$analytics['mix']['sources']);sc_ei_analytics_group('Inquiry types',$analytics['mix']['types']);sc_ei_analytics_group('Service interests',$analytics['mix']['services']);sc_ei_analytics_group('Inquiry status',$analytics['mix']['statuses']);sc_ei_analytics_group('Finalized fit recommendations',$analytics['mix']['fit']);sc_ei_analytics_group('Engagement lifecycle',$analytics['mix']['engagements']);?></div>
<div class="sc-ei-analytics-grid"><section class="sc-ei-admin__card"><h2>Median cycle time</h2><dl class="sc-ei-admin__details"><dt>Inquiry to review start</dt><dd><?php echo esc_html($analytics['timing']['median_hours_to_review_start']??'—');?> hours</dd><dt>Inquiry to decision</dt><dd><?php echo esc_html($analytics['timing']['median_hours_to_decision']??'—');?> hours</dd><dt>Proposal to contract</dt><dd><?php echo esc_html($analytics['timing']['median_hours_proposal_to_contract']??'—');?> hours</dd></dl></section><section class="sc-ei-admin__card"><h2>Operational attention</h2><dl class="sc-ei-admin__details"><?php foreach($analytics['operations'] as $k=>$v):?><dt><?php echo esc_html(ucwords(str_replace('_',' ',$k)));?></dt><dd><?php echo esc_html(number_format_i18n($v));?></dd><?php endforeach;?></dl></section><section class="sc-ei-admin__card"><h2>Communication volume</h2><dl class="sc-ei-admin__details"><dt>Outbound records</dt><dd><?php echo esc_html(number_format_i18n($analytics['communications']['outbound']));?></dd><dt>Inbound records</dt><dd><?php echo esc_html(number_format_i18n($analytics['communications']['inbound']));?></dd></dl></section></div>
<?php if(current_user_can('sc_intake_manage_analytics')):?><section class="sc-ei-admin__card"><h2>Auditable snapshot</h2><p>Save the current aggregate payload and SHA-256 hash. Snapshots contain no direct identifiers or content bodies.</p><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>" class="sc-ei-inline-confirm-form"><input type="hidden" name="action" value="sc_ei_analytics_snapshot"><input type="hidden" name="days" value="<?php echo esc_attr($analytics['range_days']);?>"><?php wp_nonce_field('sc_ei_analytics_snapshot');?><input type="text" name="confirmation" placeholder="SNAPSHOT ANALYTICS" required><button class="button button-primary">Save snapshot</button></form><table class="widefat striped"><thead><tr><th>Generated</th><th>Range</th><th>Minimum cohort</th><th>Hash</th></tr></thead><tbody><?php foreach($snapshots as $s):?><tr><td><?php echo esc_html($s['generated_at']);?> UTC</td><td><?php echo esc_html($s['range_days']);?> days</td><td><?php echo esc_html($s['minimum_cohort']);?></td><td><code><?php echo esc_html($s['content_hash']);?></code></td></tr><?php endforeach;?></tbody></table></section><?php endif;?></div>
