<?php if ( ! defined( 'ABSPATH' ) ) exit; ?>
<div class="wrap sc-ei-admin-wrap">
	<h1><?php esc_html_e( 'Billing, Invoicing, and Payment Handoffs', 'sustainable-catalyst-engagement-intake' ); ?></h1>
	<p><?php esc_html_e( 'Create governed invoice records and external payment handoffs without storing card numbers, bank credentials, or payment-provider secrets in WordPress.', 'sustainable-catalyst-engagement-intake' ); ?></p>
	<div class="sc-ei-stat-grid">
		<?php foreach ( $metrics as $label => $value ) : ?><div class="sc-ei-stat"><strong><?php echo esc_html( number_format_i18n( absint( $value ) ) ); ?></strong><span><?php echo esc_html( ucwords( str_replace( '_', ' ', $label ) ) ); ?></span></div><?php endforeach; ?>
	</div>
	<?php if ( array_sum( array_map( 'absint', $blockers ) ) ) : ?><div class="notice notice-error"><p><strong><?php esc_html_e( 'Billing integrity blockers require review.', 'sustainable-catalyst-engagement-intake' ); ?></strong> <?php echo esc_html( wp_json_encode( $blockers ) ); ?></p></div><?php endif; ?>
	<div class="sc-ei-admin-grid">
		<section class="sc-ei-admin-card"><h2><?php esc_html_e( 'Invoices', 'sustainable-catalyst-engagement-intake' ); ?></h2><?php if(!$invoices):?><p><?php esc_html_e('No invoices yet.','sustainable-catalyst-engagement-intake');?></p><?php endif;?><table class="widefat striped"><thead><tr><th><?php esc_html_e('Invoice','sustainable-catalyst-engagement-intake');?></th><th><?php esc_html_e('Status','sustainable-catalyst-engagement-intake');?></th><th><?php esc_html_e('Total','sustainable-catalyst-engagement-intake');?></th></tr></thead><tbody><?php foreach($invoices as $row):?><tr><td><a href="<?php echo esc_url(add_query_arg(array('page'=>'sc-engagement-intake-billing','invoice_id'=>$row['id']),admin_url('admin.php')));?>"><?php echo esc_html($row['invoice_number']);?></a></td><td><?php echo esc_html(ucwords(str_replace('_',' ',$row['status'])));?></td><td><?php echo esc_html($row['currency'].' '.number_format(absint($row['total_minor'])/100,2));?></td></tr><?php endforeach;?></tbody></table></section>
		<section class="sc-ei-admin-card"><h2><?php esc_html_e( 'Create billing profile', 'sustainable-catalyst-engagement-intake' ); ?></h2><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="sc_ei_billing_create_profile"><?php wp_nonce_field('sc_ei_billing_create_profile');?><label><span><?php esc_html_e('Engagement','sustainable-catalyst-engagement-intake');?></span><select name="engagement_id" required><option value=""><?php esc_html_e('Select','sustainable-catalyst-engagement-intake');?></option><?php foreach($engagements as $e):?><option value="<?php echo esc_attr($e['id']);?>"><?php echo esc_html(($e['engagement_number']??('#'.$e['id'])).' — '.($e['title']??''));?></option><?php endforeach;?></select></label><label><span><?php esc_html_e('Organization','sustainable-catalyst-engagement-intake');?></span><input name="organization_name" required></label><label><span><?php esc_html_e('Billing contact','sustainable-catalyst-engagement-intake');?></span><input name="billing_contact_name"></label><label><span><?php esc_html_e('Billing email','sustainable-catalyst-engagement-intake');?></span><input type="email" name="billing_contact_email"></label><label><span><?php esc_html_e('Currency','sustainable-catalyst-engagement-intake');?></span><input name="currency" value="USD" maxlength="3"></label><label><span><?php esc_html_e('Payment terms (days)','sustainable-catalyst-engagement-intake');?></span><input type="number" name="payment_terms_days" value="30" min="0" max="365"></label><button class="button button-primary"><?php esc_html_e('Create profile','sustainable-catalyst-engagement-intake');?></button></form></section>
	</div>
	<?php if ( $invoice ) : ?>
	<section class="sc-ei-admin-card"><h2><?php echo esc_html($invoice['invoice_number']);?></h2><p><?php echo esc_html($invoice['currency'].' '.number_format(absint($invoice['total_minor'])/100,2).' · '.ucwords(str_replace('_',' ',$invoice['status'])));?></p><h3><?php esc_html_e('Line items','sustainable-catalyst-engagement-intake');?></h3><ul><?php foreach($items as $item):?><li><?php echo esc_html($item['description'].' — '.$invoice['currency'].' '.number_format(absint($item['amount_minor'])/100,2));?></li><?php endforeach;?></ul>
	<form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="sc_ei_billing_add_item"><input type="hidden" name="invoice_id" value="<?php echo esc_attr($invoice['id']);?>"><?php wp_nonce_field('sc_ei_billing_add_item_'.$invoice['id']);?><label><span><?php esc_html_e('Description','sustainable-catalyst-engagement-intake');?></span><input name="description" required></label><label><span><?php esc_html_e('Quantity','sustainable-catalyst-engagement-intake');?></span><input name="quantity" type="number" step="0.0001" value="1"></label><label><span><?php esc_html_e('Unit amount, minor currency units','sustainable-catalyst-engagement-intake');?></span><input name="unit_amount_minor" type="number" min="0" required></label><button class="button"><?php esc_html_e('Add item','sustainable-catalyst-engagement-intake');?></button></form>
	<form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="sc_ei_billing_transition"><input type="hidden" name="invoice_id" value="<?php echo esc_attr($invoice['id']);?>"><?php wp_nonce_field('sc_ei_billing_transition_'.$invoice['id']);?><label><span><?php esc_html_e('Next status','sustainable-catalyst-engagement-intake');?></span><select name="status"><?php foreach(SC_EI_Billing_Schema::allowed_transitions()[$invoice['status']]??array() as $status):?><option value="<?php echo esc_attr($status);?>"><?php echo esc_html(SC_EI_Billing_Schema::invoice_statuses()[$status]??$status);?></option><?php endforeach;?></select></label><label><span><?php esc_html_e('Note','sustainable-catalyst-engagement-intake');?></span><textarea name="note"></textarea></label><label><span><?php echo esc_html__('Typed confirmation uses: STATUS INVOICE-NUMBER','sustainable-catalyst-engagement-intake');?></span><input name="confirmation" required></label><button class="button button-primary"><?php esc_html_e('Record transition','sustainable-catalyst-engagement-intake');?></button></form>
	<?php if(in_array($invoice['status'],array('issued','partially_paid','overdue','disputed'),true)):?><h3><?php esc_html_e('External payment handoff','sustainable-catalyst-engagement-intake');?></h3><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="sc_ei_billing_create_handoff"><input type="hidden" name="invoice_id" value="<?php echo esc_attr($invoice['id']);?>"><?php wp_nonce_field('sc_ei_billing_create_handoff_'.$invoice['id']);?><label><span><?php esc_html_e('Provider','sustainable-catalyst-engagement-intake');?></span><select name="provider"><?php foreach(SC_EI_Billing_Schema::providers() as $key=>$label):?><option value="<?php echo esc_attr($key);?>"><?php echo esc_html($label);?></option><?php endforeach;?></select></label><label><span><?php esc_html_e('Provider reference','sustainable-catalyst-engagement-intake');?></span><input name="provider_reference"></label><label><span><?php esc_html_e('HTTPS checkout or invoice URL','sustainable-catalyst-engagement-intake');?></span><input type="url" name="checkout_url"></label><label><span><?php esc_html_e('Amount, minor units','sustainable-catalyst-engagement-intake');?></span><input type="number" name="amount_minor" value="<?php echo esc_attr($invoice['balance_due_minor']);?>"></label><label class="sc-ei-check"><input type="checkbox" name="sender_visible" value="1"><span><?php esc_html_e('Publish this handoff to the Sender Portal','sustainable-catalyst-engagement-intake');?></span></label><button class="button"><?php esc_html_e('Create handoff','sustainable-catalyst-engagement-intake');?></button></form><?php endif;?>
	</section>
	<?php endif; ?>
	<section class="sc-ei-admin-card"><h2><?php esc_html_e('Create invoice','sustainable-catalyst-engagement-intake');?></h2><p><?php esc_html_e('Create a billing profile first, then supply its numeric ID. This deliberately avoids automatic charging or payment collection.','sustainable-catalyst-engagement-intake');?></p><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><input type="hidden" name="action" value="sc_ei_billing_create_invoice"><?php wp_nonce_field('sc_ei_billing_create_invoice');?><label><span><?php esc_html_e('Engagement','sustainable-catalyst-engagement-intake');?></span><select name="engagement_id" required><?php foreach($engagements as $e):?><option value="<?php echo esc_attr($e['id']);?>"><?php echo esc_html(($e['engagement_number']??('#'.$e['id'])).' — '.($e['title']??''));?></option><?php endforeach;?></select></label><label><span><?php esc_html_e('Billing profile ID','sustainable-catalyst-engagement-intake');?></span><input type="number" name="billing_profile_id" min="1" required></label><label><span><?php esc_html_e('Currency','sustainable-catalyst-engagement-intake');?></span><input name="currency" value="USD" maxlength="3"></label><label><span><?php esc_html_e('Due date','sustainable-catalyst-engagement-intake');?></span><input type="datetime-local" name="due_at"></label><label><span><?php esc_html_e('Sender memo','sustainable-catalyst-engagement-intake');?></span><textarea name="memo"></textarea></label><label><span><?php esc_html_e('Internal note','sustainable-catalyst-engagement-intake');?></span><textarea name="internal_note"></textarea></label><button class="button button-primary"><?php esc_html_e('Create invoice','sustainable-catalyst-engagement-intake');?></button></form></section>
</div>
