<?php
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}
$success = array(
	'calendar_coordination_saved' => __( 'Meeting coordination details saved.', 'sustainable-catalyst-engagement-intake' ),
	'calendar_meeting_rescheduled'=> __( 'Meeting rescheduled and reminder evidence regenerated.', 'sustainable-catalyst-engagement-intake' ),
	'calendar_meeting_completed'  => __( 'Meeting completion and follow-up were recorded.', 'sustainable-catalyst-engagement-intake' ),
	'calendar_meeting_canceled'   => __( 'Meeting canceled and active join links revoked from the portal.', 'sustainable-catalyst-engagement-intake' ),
	'calendar_reminder_marked_sent'=> __( 'Reminder linked to a reviewed communication record.', 'sustainable-catalyst-engagement-intake' ),
);
?>
<div class="wrap sc-ei-admin sc-ei-calendar-admin">
	<h1><?php esc_html_e( 'Microsoft Teams and Calendar Coordination', 'sustainable-catalyst-engagement-intake' ); ?></h1>
	<p><?php esc_html_e( 'Coordinate reviewed meetings, explicit time zones, sender-visible agendas, Microsoft Teams links, calendar references, reminders, rescheduling history, and post-meeting follow-up. This workspace does not expose a public booking calendar or send reminders automatically.', 'sustainable-catalyst-engagement-intake' ); ?></p>
	<p class="description"><?php esc_html_e( 'Local times skipped or repeated during daylight-saving transitions are rejected instead of being silently shifted.', 'sustainable-catalyst-engagement-intake' ); ?></p>
	<?php if ( isset( $success[ $message ] ) ) : ?><div class="notice notice-success is-dismissible"><p><?php echo esc_html( $success[ $message ] ); ?></p></div><?php elseif ( $message ) : ?><div class="notice notice-error is-dismissible"><p><?php echo esc_html( ucwords( str_replace( '_', ' ', $message ) ) ); ?></p></div><?php endif; ?>

	<div class="sc-ei-portal-admin-boundary"><strong><?php esc_html_e( 'Coordination boundary', 'sustainable-catalyst-engagement-intake' ); ?></strong><span><?php esc_html_e( 'Meeting offers remain review-first. Calendar creation through Microsoft Graph is a separate authorized action. Reminder records become ready for human review and are not automatically emailed. Canceling a meeting removes its active Teams link from the Sender Portal.', 'sustainable-catalyst-engagement-intake' ); ?></span></div>

	<div class="sc-ei-fit-metrics">
		<div><strong><?php echo esc_html( number_format_i18n( $metrics['scheduled'] ) ); ?></strong><span><?php esc_html_e( 'scheduled', 'sustainable-catalyst-engagement-intake' ); ?></span></div>
		<div><strong><?php echo esc_html( number_format_i18n( $metrics['next_seven_days'] ) ); ?></strong><span><?php esc_html_e( 'next seven days', 'sustainable-catalyst-engagement-intake' ); ?></span></div>
		<div class="<?php echo $metrics['reminders_ready'] ? 'sc-ei-review-metric--attention' : ''; ?>"><strong><?php echo esc_html( number_format_i18n( $metrics['reminders_ready'] ) ); ?></strong><span><?php esc_html_e( 'reminders ready', 'sustainable-catalyst-engagement-intake' ); ?></span></div>
		<div class="<?php echo $metrics['graph_reconcile_due'] ? 'sc-ei-review-metric--attention' : ''; ?>"><strong><?php echo esc_html( number_format_i18n( $metrics['graph_reconcile_due'] ) ); ?></strong><span><?php esc_html_e( 'Graph actions due', 'sustainable-catalyst-engagement-intake' ); ?></span></div>
		<div class="<?php echo $metrics['follow_up_overdue'] ? 'sc-ei-review-metric--attention' : ''; ?>"><strong><?php echo esc_html( number_format_i18n( $metrics['follow_up_overdue'] ) ); ?></strong><span><?php esc_html_e( 'follow-up attention', 'sustainable-catalyst-engagement-intake' ); ?></span></div>
	</div>

	<section class="sc-ei-admin__card sc-ei-admin__card--wide">
		<h2><?php esc_html_e( 'Open an Inquiry Calendar', 'sustainable-catalyst-engagement-intake' ); ?></h2>
		<form method="get" class="sc-ei-operation-filter-form"><input type="hidden" name="page" value="sc-engagement-intake-calendar"><label><span class="screen-reader-text"><?php esc_html_e( 'Inquiry ID', 'sustainable-catalyst-engagement-intake' ); ?></span><input type="number" name="inquiry" min="1" value="<?php echo esc_attr( $inquiry_id ?: '' ); ?>" placeholder="<?php esc_attr_e( 'Inquiry ID', 'sustainable-catalyst-engagement-intake' ); ?>" required></label><button type="submit" class="button button-primary"><?php esc_html_e( 'Open Calendar', 'sustainable-catalyst-engagement-intake' ); ?></button></form>
	</section>

	<?php if ( ! $inquiry_id ) : ?>
		<div class="sc-ei-admin__card sc-ei-admin__card--wide"><p><?php esc_html_e( 'Enter an inquiry ID to coordinate its Microsoft Teams meetings.', 'sustainable-catalyst-engagement-intake' ); ?></p></div>
	<?php elseif ( ! $inquiry ) : ?>
		<div class="notice notice-error"><p><?php esc_html_e( 'The inquiry could not be found.', 'sustainable-catalyst-engagement-intake' ); ?></p></div>
	<?php else : ?>
		<header class="sc-ei-admin__card sc-ei-admin__card--wide sc-ei-workflow-inquiry-header"><div><p class="sc-ei-admin__card-kicker"><?php esc_html_e( 'Selected Inquiry', 'sustainable-catalyst-engagement-intake' ); ?></p><h2><?php echo esc_html( $inquiry['reference'] . ' · ' . $inquiry['contact_name'] ); ?></h2><p><?php echo esc_html( $inquiry['contact_email'] ); ?></p></div><p><a class="button" href="<?php echo esc_url( SC_EI_Workflow_Admin::url( $inquiry_id ) ); ?>"><?php esc_html_e( 'Create Meeting Offer', 'sustainable-catalyst-engagement-intake' ); ?></a></p></header>
		<?php if ( ! $meetings ) : ?><div class="sc-ei-admin__card sc-ei-admin__card--wide"><p><?php esc_html_e( 'No meeting records exist for this inquiry. Create and publish reviewed meeting times in Teams & Proposals first.', 'sustainable-catalyst-engagement-intake' ); ?></p></div><?php endif; ?>
		<?php foreach ( $meetings as $meeting ) : $participant_emails = json_decode( (string) ( $meeting['participant_emails_json'] ?? '[]' ), true ) ?: array(); ?>
			<section class="sc-ei-admin__card sc-ei-admin__card--wide">
				<header class="sc-ei-portal-workflow-header"><div><p class="sc-ei-admin__card-kicker"><?php echo esc_html( $meeting['offer_number'] ); ?></p><h2><?php echo esc_html( $meeting['title'] ); ?></h2></div><span class="sc-ei-portal-workflow-state"><?php echo esc_html( SC_EI_Workflow_Schema::label( SC_EI_Workflow_Schema::meeting_statuses(), $meeting['status'] ) ); ?></span></header>
				<dl class="sc-ei-portal-details"><dt><?php esc_html_e( 'Type', 'sustainable-catalyst-engagement-intake' ); ?></dt><dd><?php echo esc_html( SC_EI_Calendar_Schema::label( SC_EI_Calendar_Schema::meeting_types(), (string) ( $meeting['meeting_type'] ?? 'other' ) ) ); ?></dd><dt><?php esc_html_e( 'Selected time', 'sustainable-catalyst-engagement-intake' ); ?></dt><dd><?php echo esc_html( $meeting['selected_start_utc'] ? SC_EI_Teams::format_utc_for_input( $meeting['selected_start_utc'], $meeting['timezone'] ) . ' · ' . $meeting['timezone'] : __( 'Not selected', 'sustainable-catalyst-engagement-intake' ) ); ?></dd><dt><?php esc_html_e( 'Reschedules', 'sustainable-catalyst-engagement-intake' ); ?></dt><dd><?php echo esc_html( number_format_i18n( absint( $meeting['reschedule_count'] ?? 0 ) ) ); ?></dd><dt><?php esc_html_e( 'Calendar provider', 'sustainable-catalyst-engagement-intake' ); ?></dt><dd><?php echo esc_html( SC_EI_Calendar_Schema::label( SC_EI_Calendar_Schema::providers(), (string) ( $meeting['calendar_provider'] ?? 'manual' ) ) ); ?></dd></dl>

				<form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" class="sc-ei-portal-admin-form">
					<input type="hidden" name="action" value="sc_ei_calendar_save_coordination"><input type="hidden" name="meeting_offer_id" value="<?php echo esc_attr( $meeting['id'] ); ?>"><?php wp_nonce_field( 'sc_ei_calendar_save_coordination_' . $meeting['id'] ); ?>
					<label><span><?php esc_html_e( 'Meeting type', 'sustainable-catalyst-engagement-intake' ); ?></span><select name="meeting_type"><?php foreach ( SC_EI_Calendar_Schema::meeting_types() as $key => $label ) : ?><option value="<?php echo esc_attr( $key ); ?>" <?php selected( (string) ( $meeting['meeting_type'] ?? 'other' ), $key ); ?>><?php echo esc_html( $label ); ?></option><?php endforeach; ?></select></label>
					<label><span><?php esc_html_e( 'Timezone', 'sustainable-catalyst-engagement-intake' ); ?></span><select name="meeting_timezone"><?php foreach ( SC_EI_Teams::timezone_identifiers() as $zone ) : ?><option value="<?php echo esc_attr( $zone ); ?>" <?php selected( $meeting['timezone'], $zone ); ?>><?php echo esc_html( $zone ); ?></option><?php endforeach; ?></select></label>
					<label class="sc-ei-portal-admin-form__wide"><span><?php esc_html_e( 'Microsoft Teams URL', 'sustainable-catalyst-engagement-intake' ); ?></span><input type="url" name="teams_url" value="<?php echo esc_attr( $meeting['teams_url'] ); ?>"></label>
					<label><span><?php esc_html_e( 'Organizer name', 'sustainable-catalyst-engagement-intake' ); ?></span><input type="text" name="organizer_name" value="<?php echo esc_attr( $meeting['organizer_name'] ?? '' ); ?>"></label>
					<label><span><?php esc_html_e( 'Organizer email', 'sustainable-catalyst-engagement-intake' ); ?></span><input type="email" name="organizer_email" value="<?php echo esc_attr( $meeting['organizer_email'] ?? '' ); ?>"></label>
					<label class="sc-ei-portal-admin-form__wide"><span><?php esc_html_e( 'Participant emails', 'sustainable-catalyst-engagement-intake' ); ?></span><textarea name="participant_emails" rows="3"><?php echo esc_textarea( implode( "\n", $participant_emails ) ); ?></textarea></label>
					<label class="sc-ei-portal-admin-form__wide"><span><?php esc_html_e( 'Sender-visible agenda', 'sustainable-catalyst-engagement-intake' ); ?></span><textarea name="agenda" rows="5"><?php echo esc_textarea( $meeting['agenda'] ?? '' ); ?></textarea></label>
					<label class="sc-ei-portal-admin-form__wide"><span><?php esc_html_e( 'Preparation requests', 'sustainable-catalyst-engagement-intake' ); ?></span><textarea name="preparation_requests" rows="4"><?php echo esc_textarea( $meeting['preparation_requests'] ?? '' ); ?></textarea></label>
					<label class="sc-ei-portal-admin-form__wide"><span><?php esc_html_e( 'Sender-visible summary', 'sustainable-catalyst-engagement-intake' ); ?></span><textarea name="sender_summary" rows="4"><?php echo esc_textarea( $meeting['sender_summary'] ?? '' ); ?></textarea></label>
					<label class="sc-ei-portal-admin-form__wide"><span><?php esc_html_e( 'Sender-visible next step', 'sustainable-catalyst-engagement-intake' ); ?></span><textarea name="sender_next_step" rows="3"><?php echo esc_textarea( $meeting['sender_next_step'] ?? '' ); ?></textarea></label>
					<label><span><?php esc_html_e( 'Calendar provider', 'sustainable-catalyst-engagement-intake' ); ?></span><select name="calendar_provider"><?php foreach ( SC_EI_Calendar_Schema::providers() as $key => $label ) : ?><option value="<?php echo esc_attr( $key ); ?>" <?php selected( (string) ( $meeting['calendar_provider'] ?? 'manual' ), $key ); ?>><?php echo esc_html( $label ); ?></option><?php endforeach; ?></select></label>
					<label><span><?php esc_html_e( 'External calendar reference', 'sustainable-catalyst-engagement-intake' ); ?></span><input type="text" name="external_calendar_reference" value="<?php echo esc_attr( $meeting['external_calendar_reference'] ?? '' ); ?>"></label>
					<label class="sc-ei-portal-admin-form__wide"><span><?php esc_html_e( 'Related document IDs', 'sustainable-catalyst-engagement-intake' ); ?></span><input type="text" name="related_document_ids" value="<?php echo esc_attr( implode( ', ', json_decode( (string) ( $meeting['related_document_ids_json'] ?? '[]' ), true ) ?: array() ) ); ?>"></label>
					<button type="submit" class="button button-primary"><?php esc_html_e( 'Save Coordination Details', 'sustainable-catalyst-engagement-intake' ); ?></button>
				</form>

				<?php if ( in_array( $meeting['status'], array( 'accepted_pending_link', 'scheduled' ), true ) ) : ?>
					<details><summary><?php esc_html_e( 'Reschedule meeting', 'sustainable-catalyst-engagement-intake' ); ?></summary><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" class="sc-ei-portal-admin-form"><input type="hidden" name="action" value="sc_ei_calendar_reschedule"><input type="hidden" name="meeting_offer_id" value="<?php echo esc_attr( $meeting['id'] ); ?>"><?php wp_nonce_field( 'sc_ei_calendar_reschedule_' . $meeting['id'] ); ?><label><span><?php esc_html_e( 'New start', 'sustainable-catalyst-engagement-intake' ); ?></span><input type="datetime-local" name="start_local" required></label><label><span><?php esc_html_e( 'New end', 'sustainable-catalyst-engagement-intake' ); ?></span><input type="datetime-local" name="end_local" required></label><label><span><?php esc_html_e( 'Timezone', 'sustainable-catalyst-engagement-intake' ); ?></span><select name="timezone"><?php foreach ( SC_EI_Teams::timezone_identifiers() as $zone ) : ?><option value="<?php echo esc_attr( $zone ); ?>" <?php selected( $meeting['timezone'], $zone ); ?>><?php echo esc_html( $zone ); ?></option><?php endforeach; ?></select></label><label class="sc-ei-portal-admin-form__wide"><span><?php esc_html_e( 'Reason', 'sustainable-catalyst-engagement-intake' ); ?></span><textarea name="reason" rows="3" required></textarea></label><label class="sc-ei-portal-admin-form__wide"><span><?php echo esc_html( 'Type RESCHEDULE ' . strtoupper( $meeting['offer_number'] ) ); ?></span><input type="text" name="confirmation" required autocomplete="off"></label><button type="submit" class="button"><?php esc_html_e( 'Reschedule Meeting', 'sustainable-catalyst-engagement-intake' ); ?></button></form></details>
				<?php endif; ?>

				<?php if ( 'scheduled' === $meeting['status'] ) : ?>
					<details><summary><?php esc_html_e( 'Complete meeting and create follow-up', 'sustainable-catalyst-engagement-intake' ); ?></summary><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" class="sc-ei-portal-admin-form"><input type="hidden" name="action" value="sc_ei_calendar_complete"><input type="hidden" name="meeting_offer_id" value="<?php echo esc_attr( $meeting['id'] ); ?>"><?php wp_nonce_field( 'sc_ei_calendar_complete_' . $meeting['id'] ); ?><label class="sc-ei-portal-admin-form__wide"><span><?php esc_html_e( 'Private internal notes', 'sustainable-catalyst-engagement-intake' ); ?></span><textarea name="internal_notes" rows="5"></textarea></label><label class="sc-ei-portal-admin-form__wide"><span><?php esc_html_e( 'Sender-visible meeting summary', 'sustainable-catalyst-engagement-intake' ); ?></span><textarea name="sender_summary" rows="4"></textarea></label><label class="sc-ei-portal-admin-form__wide"><span><?php esc_html_e( 'Decisions', 'sustainable-catalyst-engagement-intake' ); ?></span><textarea name="decisions" rows="3"></textarea></label><label class="sc-ei-portal-admin-form__wide"><span><?php esc_html_e( 'Open questions', 'sustainable-catalyst-engagement-intake' ); ?></span><textarea name="open_questions" rows="3"></textarea></label><label><span><?php esc_html_e( 'Follow-up task title', 'sustainable-catalyst-engagement-intake' ); ?></span><input type="text" name="follow_up_title"></label><label><span><?php esc_html_e( 'Follow-up owner user ID', 'sustainable-catalyst-engagement-intake' ); ?></span><input type="number" min="0" name="follow_up_owner_user_id" value="<?php echo esc_attr( get_current_user_id() ); ?>"></label><label><span><?php esc_html_e( 'Follow-up due', 'sustainable-catalyst-engagement-intake' ); ?></span><input type="datetime-local" name="follow_up_due_at"></label><label class="sc-ei-portal-admin-form__wide"><span><?php esc_html_e( 'Follow-up details', 'sustainable-catalyst-engagement-intake' ); ?></span><textarea name="follow_up_details" rows="3"></textarea></label><label class="sc-ei-portal-admin-form__wide"><span><?php echo esc_html( 'Type COMPLETE ' . strtoupper( $meeting['offer_number'] ) ); ?></span><input type="text" name="confirmation" required autocomplete="off"></label><button type="submit" class="button button-primary"><?php esc_html_e( 'Complete and Record Follow-Up', 'sustainable-catalyst-engagement-intake' ); ?></button></form></details>
				<?php endif; ?>

				<?php if ( ! in_array( $meeting['status'], array( 'completed', 'canceled', 'expired', 'superseded' ), true ) ) : ?>
					<details><summary><?php esc_html_e( 'Cancel meeting', 'sustainable-catalyst-engagement-intake' ); ?></summary><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" class="sc-ei-portal-admin-form"><input type="hidden" name="action" value="sc_ei_calendar_cancel"><input type="hidden" name="meeting_offer_id" value="<?php echo esc_attr( $meeting['id'] ); ?>"><?php wp_nonce_field( 'sc_ei_calendar_cancel_' . $meeting['id'] ); ?><label class="sc-ei-portal-admin-form__wide"><span><?php esc_html_e( 'Cancellation reason', 'sustainable-catalyst-engagement-intake' ); ?></span><textarea name="reason" rows="3" required></textarea></label><label class="sc-ei-portal-admin-form__wide"><span><?php echo esc_html( 'Type CANCEL ' . strtoupper( $meeting['offer_number'] ) ); ?></span><input type="text" name="confirmation" required autocomplete="off"></label><button type="submit" class="button"><?php esc_html_e( 'Cancel and Revoke Portal Link', 'sustainable-catalyst-engagement-intake' ); ?></button></form></details>
				<?php endif; ?>

				<h3><?php esc_html_e( 'Reminder Evidence', 'sustainable-catalyst-engagement-intake' ); ?></h3>
				<?php if ( empty( $reminders[ $meeting['id'] ] ) ) : ?><p><?php esc_html_e( 'No reminder records are available. They are generated when a meeting is scheduled or rescheduled.', 'sustainable-catalyst-engagement-intake' ); ?></p><?php else : ?><table class="widefat striped"><thead><tr><th><?php esc_html_e( 'Type', 'sustainable-catalyst-engagement-intake' ); ?></th><th><?php esc_html_e( 'Due', 'sustainable-catalyst-engagement-intake' ); ?></th><th><?php esc_html_e( 'Status', 'sustainable-catalyst-engagement-intake' ); ?></th><th><?php esc_html_e( 'Communication', 'sustainable-catalyst-engagement-intake' ); ?></th></tr></thead><tbody><?php foreach ( $reminders[ $meeting['id'] ] as $reminder ) : ?><tr><td><?php echo esc_html( SC_EI_Calendar_Schema::label( SC_EI_Calendar_Schema::reminder_types(), $reminder['reminder_type'] ) ); ?></td><td><?php echo esc_html( $reminder['due_at'] ); ?> UTC</td><td><?php echo esc_html( SC_EI_Calendar_Schema::label( SC_EI_Calendar_Schema::reminder_statuses(), $reminder['status'] ) ); ?></td><td><?php if ( 'ready_for_review' === $reminder['status'] && current_user_can( 'sc_intake_send_communications' ) ) : ?><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><input type="hidden" name="action" value="sc_ei_calendar_mark_reminder_sent"><input type="hidden" name="reminder_id" value="<?php echo esc_attr( $reminder['id'] ); ?>"><input type="hidden" name="meeting_offer_id" value="<?php echo esc_attr( $meeting['id'] ); ?>"><?php wp_nonce_field( 'sc_ei_calendar_mark_reminder_sent_' . $reminder['id'] ); ?><label><span class="screen-reader-text"><?php esc_html_e( 'Communication ID', 'sustainable-catalyst-engagement-intake' ); ?></span><input type="number" min="1" name="communication_id" required placeholder="<?php esc_attr_e( 'Communication ID', 'sustainable-catalyst-engagement-intake' ); ?>"></label><button type="submit" class="button button-small"><?php esc_html_e( 'Mark Sent', 'sustainable-catalyst-engagement-intake' ); ?></button></form><?php else : ?><?php echo esc_html( $reminder['communication_id'] ?: '—' ); ?><?php endif; ?></td></tr><?php endforeach; ?></tbody></table><?php endif; ?>
			</section>
		<?php endforeach; ?>
	<?php endif; ?>
</div>
