<?php
if ( ! defined( 'ABSPATH' ) ) exit;
$message = sanitize_key( $_GET['sc_ei_msg'] ?? '' );
$labels = static function ( array $values ): string { return $values ? implode( ' · ', array_map( static fn( $k, $v ): string => ucwords( str_replace( '_', ' ', (string) $k ) ) . ': ' . number_format_i18n( (int) $v ), array_keys( $values ), array_values( $values ) ) ) : 'None'; };
?>
<div class="wrap sc-ei-admin sc-ei-command-center">
<header class="sc-ei-admin__header"><div><p class="sc-ei-admin__eyebrow">Integrated Platform v2.0</p><h1>Engagement Command Center</h1><p>One canonical dossier and activity timeline across contact, advisory, product support, Teams scheduling, proposals, client collaboration, billing, privacy, and service intelligence.</p></div><div class="sc-ei-admin__version">v2.0.0</div></header>
<?php if ( $message ) : ?><div class="notice notice-success"><p><?php echo esc_html( ucwords( str_replace( '_', ' ', $message ) ) ); ?></p></div><?php endif; ?>
<div class="sc-ei-portal-admin-boundary"><strong>Governance boundary</strong><span>The command center unifies evidence; it does not merge private cases, rank senders, make fit decisions, schedule meetings, approve proposals, issue invoices, collect payment, or expose internal records automatically.</span></div>
<div class="sc-ei-review-metrics">
<a><strong><?php echo esc_html( number_format_i18n( (int) $dashboard['total'] ) ); ?></strong><span>Dossiers</span></a>
<a><strong><?php echo esc_html( number_format_i18n( (int) ( $dashboard['integrity']['missing_dossiers'] ?? 0 ) ) ); ?></strong><span>Missing dossiers</span></a>
<a><strong><?php echo esc_html( number_format_i18n( (int) ( $dashboard['integrity']['failed_handoffs'] ?? 0 ) ) ); ?></strong><span>Failed handoffs</span></a>
<a><strong><?php echo esc_html( number_format_i18n( (int) ( $dashboard['by_health']['blocked'] ?? 0 ) ) ); ?></strong><span>Blocked dossiers</span></a>
</div>
<div class="sc-ei-analytics-grid">
<section class="sc-ei-admin__card"><h2>By route</h2><p><?php echo esc_html( $labels( (array) $dashboard['by_route'] ) ); ?></p></section>
<section class="sc-ei-admin__card"><h2>By phase</h2><p><?php echo esc_html( $labels( (array) $dashboard['by_phase'] ) ); ?></p></section>
<section class="sc-ei-admin__card"><h2>Integrity</h2><p><?php echo esc_html( $labels( (array) $dashboard['integrity'] ) ); ?></p><?php if ( current_user_can( 'sc_intake_manage_platform' ) ) : ?><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><input type="hidden" name="action" value="sc_ei_unified_backfill"><?php wp_nonce_field( 'sc_ei_unified_backfill' ); ?><button class="button">Rebuild all dossiers</button></form><?php endif; ?></section>
</div>
<form method="get" class="sc-ei-operation-filter-form"><input type="hidden" name="page" value="sc-engagement-intake-command-center"><input type="search" name="s" value="<?php echo esc_attr( $_GET['s'] ?? '' ); ?>" placeholder="Reference or sender-safe summary"><select name="route_group"><option value="">All routes</option><?php foreach ( SC_EI_Unified_Platform_Schema::route_groups() as $key => $label ) : ?><option value="<?php echo esc_attr( $key ); ?>" <?php selected( $_GET['route_group'] ?? '', $key ); ?>><?php echo esc_html( $label ); ?></option><?php endforeach; ?></select><select name="phase"><option value="">All phases</option><?php foreach ( SC_EI_Unified_Platform_Schema::phases() as $key => $label ) : ?><option value="<?php echo esc_attr( $key ); ?>" <?php selected( $_GET['phase'] ?? '', $key ); ?>><?php echo esc_html( $label ); ?></option><?php endforeach; ?></select><button class="button">Filter</button></form>
<section class="sc-ei-admin__card sc-ei-admin__card--wide"><h2>Canonical engagement dossiers</h2><table class="widefat striped"><thead><tr><th>Reference</th><th>Route</th><th>Phase</th><th>Health</th><th>Relationships</th><th>Updated</th></tr></thead><tbody><?php if ( ! $dossiers ) : ?><tr><td colspan="6">No dossiers found. Run the bounded rebuild after migration.</td></tr><?php endif; ?><?php foreach ( $dossiers as $row ) : ?><tr><td><a href="<?php echo esc_url( add_query_arg( array( 'page' => 'sc-engagement-intake-command-center', 'dossier_id' => $row['id'] ), admin_url( 'admin.php' ) ) ); ?>"><strong><?php echo esc_html( $row['reference'] ); ?></strong></a><br><code><?php echo esc_html( $row['public_id'] ); ?></code></td><td><?php echo esc_html( ucwords( str_replace( '_', ' ', $row['route_group'] ) ) ); ?></td><td><?php echo esc_html( ucwords( str_replace( '_', ' ', $row['phase'] ) ) ); ?></td><td><?php echo esc_html( ucfirst( $row['health_status'] ) ); ?></td><td><?php echo esc_html( number_format_i18n( (int) $row['relationship_count'] ) ); ?></td><td><?php echo esc_html( $row['updated_at'] ); ?> UTC</td></tr><?php endforeach; ?></tbody></table></section>
<?php if ( $dossier ) : ?>
<section class="sc-ei-admin__card sc-ei-admin__card--wide"><h2>Dossier <?php echo esc_html( $dossier['reference'] ); ?></h2><dl class="sc-ei-admin__details"><dt>Route</dt><dd><?php echo esc_html( $dossier['route_group'] ); ?></dd><dt>Phase</dt><dd><?php echo esc_html( $dossier['phase'] ); ?></dd><dt>Health</dt><dd><?php echo esc_html( $dossier['health_status'] ); ?></dd><dt>Sender summary</dt><dd><?php echo esc_html( $dossier['sender_summary'] ?: '—' ); ?></dd><dt>Next step</dt><dd><?php echo esc_html( $dossier['sender_next_step'] ?: '—' ); ?></dd><dt>Evidence hash</dt><dd><code><?php echo esc_html( $dossier['content_hash'] ); ?></code></dd></dl><?php if ( current_user_can( 'sc_intake_manage_platform' ) ) : ?><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>"><input type="hidden" name="action" value="sc_ei_unified_refresh_dossier"><input type="hidden" name="dossier_id" value="<?php echo esc_attr( $dossier['id'] ); ?>"><?php wp_nonce_field( 'sc_ei_unified_refresh_dossier_' . $dossier['id'] ); ?><button class="button button-primary">Refresh dossier evidence</button></form><?php endif; ?></section>
<div class="sc-ei-analytics-grid"><section class="sc-ei-admin__card"><h2>Relationships</h2><ul><?php foreach ( (array) $dossier['relationships'] as $rel ) : ?><li><strong><?php echo esc_html( ucwords( str_replace( '_', ' ', $rel['entity_type'] ) ) ); ?></strong> #<?php echo esc_html( $rel['entity_id'] ); ?> · <?php echo esc_html( $rel['entity_status'] ?: 'recorded' ); ?></li><?php endforeach; ?></ul></section><section class="sc-ei-admin__card"><h2>Unified activity timeline</h2><ol><?php foreach ( array_slice( (array) $dossier['timeline'], 0, 100 ) as $event ) : ?><li><strong><?php echo esc_html( ucwords( str_replace( '_', ' ', (string) $event['type'] ) ) ); ?></strong> <span><?php echo esc_html( (string) $event['occurred_at'] ); ?> UTC</span><br><?php echo esc_html( (string) $event['summary'] ); ?></li><?php endforeach; ?></ol></section></div>
<?php endif; ?>
</div>
