<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
$messages = array(
	'support_case_updated' => __( 'Support case context updated.', 'sustainable-catalyst-engagement-intake' ),
	'support_stage_changed' => __( 'Support stage changed and audited.', 'sustainable-catalyst-engagement-intake' ),
	'support_link_added' => __( 'Support relationship added.', 'sustainable-catalyst-engagement-intake' ),
	'support_signal_added' => __( 'Privacy-safe product-intelligence signal recorded.', 'sustainable-catalyst-engagement-intake' ),
);
$environment = $selected ? json_decode( (string) $selected['environment_json'], true ) : array();
$environment = is_array( $environment ) ? $environment : array();
?>
<div class="wrap sc-ei-admin-wrap">
	<h1><?php esc_html_e( 'Support Operations and Product Intelligence', 'sustainable-catalyst-engagement-intake' ); ?></h1>
	<p><?php esc_html_e( 'Manage private product-support cases, preserve version and diagnostic context, link public documentation and feature intelligence, and publish only approved sender-safe updates.', 'sustainable-catalyst-engagement-intake' ); ?></p>
	<?php if ( $message ) : ?><div class="notice <?php echo isset( $messages[ $message ] ) ? 'notice-success' : 'notice-error'; ?> is-dismissible"><p><?php echo esc_html( $messages[ $message ] ?? ucwords( str_replace( '_', ' ', $message ) ) ); ?></p></div><?php endif; ?>
	<div class="sc-ei-metric-grid">
		<div class="sc-ei-metric"><strong><?php echo esc_html( number_format_i18n( $metrics['total'] ?? 0 ) ); ?></strong><span><?php esc_html_e( 'Support cases', 'sustainable-catalyst-engagement-intake' ); ?></span></div>
		<div class="sc-ei-metric"><strong><?php echo esc_html( number_format_i18n( $metrics['untriaged'] ?? 0 ) ); ?></strong><span><?php esc_html_e( 'Untriaged', 'sustainable-catalyst-engagement-intake' ); ?></span></div>
		<div class="sc-ei-metric"><strong><?php echo esc_html( number_format_i18n( $metrics['high_priority'] ?? 0 ) ); ?></strong><span><?php esc_html_e( 'High or critical', 'sustainable-catalyst-engagement-intake' ); ?></span></div>
		<div class="sc-ei-metric"><strong><?php echo esc_html( number_format_i18n( $metrics['awaiting_sender'] ?? 0 ) ); ?></strong><span><?php esc_html_e( 'Awaiting sender', 'sustainable-catalyst-engagement-intake' ); ?></span></div>
		<div class="sc-ei-metric"><strong><?php echo esc_html( number_format_i18n( $metrics['known_issues'] ?? 0 ) ); ?></strong><span><?php esc_html_e( 'Known issues', 'sustainable-catalyst-engagement-intake' ); ?></span></div>
		<div class="sc-ei-metric"><strong><?php echo esc_html( number_format_i18n( $metrics['signals_open'] ?? 0 ) ); ?></strong><span><?php esc_html_e( 'Open intelligence signals', 'sustainable-catalyst-engagement-intake' ); ?></span></div>
		<div class="sc-ei-metric"><strong><?php echo esc_html( number_format_i18n( $metrics['missing_product'] ?? 0 ) ); ?></strong><span><?php esc_html_e( 'Missing product', 'sustainable-catalyst-engagement-intake' ); ?></span></div>
		<div class="sc-ei-metric"><strong><?php echo esc_html( number_format_i18n( $metrics['missing_version'] ?? 0 ) ); ?></strong><span><?php esc_html_e( 'Missing version', 'sustainable-catalyst-engagement-intake' ); ?></span></div>
		<div class="sc-ei-metric"><strong><?php echo esc_html( number_format_i18n( $metrics['missing_component'] ?? 0 ) ); ?></strong><span><?php esc_html_e( 'Missing component', 'sustainable-catalyst-engagement-intake' ); ?></span></div>
		<div class="sc-ei-metric"><strong><?php echo esc_html( number_format_i18n( $metrics['failed_handoffs'] ?? 0 ) ); ?></strong><span><?php esc_html_e( 'Failed handoffs', 'sustainable-catalyst-engagement-intake' ); ?></span></div>
	</div>
	<form method="get" class="sc-ei-filter-bar"><input type="hidden" name="page" value="sc-engagement-intake-support">
		<select name="support_stage"><option value=""><?php esc_html_e( 'All stages', 'sustainable-catalyst-engagement-intake' ); ?></option><?php foreach ( SC_EI_Support_Schema::stages() as $key => $label ) : ?><option value="<?php echo esc_attr( $key ); ?>" <?php selected( $stage_filter, $key ); ?>><?php echo esc_html( $label ); ?></option><?php endforeach; ?></select>
		<select name="support_product"><option value=""><?php esc_html_e( 'All products', 'sustainable-catalyst-engagement-intake' ); ?></option><?php foreach ( SC_EI_Support_Schema::products() as $key => $label ) : ?><option value="<?php echo esc_attr( $key ); ?>" <?php selected( $product_filter, $key ); ?>><?php echo esc_html( $label ); ?></option><?php endforeach; ?></select>
		<select name="support_severity"><option value=""><?php esc_html_e( 'All severities', 'sustainable-catalyst-engagement-intake' ); ?></option><?php foreach ( SC_EI_Support_Schema::severities() as $key => $label ) : ?><option value="<?php echo esc_attr( $key ); ?>" <?php selected( $severity_filter, $key ); ?>><?php echo esc_html( $label ); ?></option><?php endforeach; ?></select>
		<input type="search" name="support_search" value="<?php echo esc_attr( $search ); ?>" placeholder="<?php esc_attr_e( 'Case, version, component, error…', 'sustainable-catalyst-engagement-intake' ); ?>"><button class="button"><?php esc_html_e( 'Filter', 'sustainable-catalyst-engagement-intake' ); ?></button>
	</form>
	<div class="sc-ei-lifecycle-layout">
		<section class="sc-ei-panel sc-ei-lifecycle-list"><h2><?php esc_html_e( 'Support queue', 'sustainable-catalyst-engagement-intake' ); ?></h2>
		<?php if ( ! $items ) : ?><p><?php esc_html_e( 'No support cases match the current filters.', 'sustainable-catalyst-engagement-intake' ); ?></p><?php endif; ?>
		<?php foreach ( $items as $item ) : ?><a class="sc-ei-lifecycle-row <?php echo $selected && absint( $selected['id'] ) === absint( $item['id'] ) ? 'is-selected' : ''; ?>" href="<?php echo esc_url( SC_EI_Support_Admin::url( absint( $item['id'] ), array( 'support_stage' => $stage_filter, 'support_product' => $product_filter, 'support_severity' => $severity_filter, 'support_search' => $search ) ) ); ?>"><strong><?php echo esc_html( $item['case_number'] . ' · ' . SC_EI_Support_Schema::label( SC_EI_Support_Schema::products(), $item['product'] ) ); ?></strong><span><?php echo esc_html( SC_EI_Support_Schema::label( SC_EI_Support_Schema::stages(), $item['workflow_stage'] ) . ' · ' . SC_EI_Support_Schema::label( SC_EI_Support_Schema::severities(), $item['severity'] ) ); ?></span><small><?php echo esc_html( $item['product_version'] . ( $item['component'] ? ' · ' . $item['component'] : '' ) ); ?></small></a><?php endforeach; ?>
		</section>
		<?php if ( $selected && $inquiry ) : ?><main class="sc-ei-lifecycle-workspace">
		<section class="sc-ei-panel"><div class="sc-ei-panel__header"><div><p class="sc-ei-eyebrow"><?php echo esc_html( $selected['case_number'] . ' · ' . $inquiry['reference'] ); ?></p><h2><?php echo esc_html( $inquiry['subject'] ?: $inquiry['contact_name'] ); ?></h2></div><span class="sc-ei-status-pill"><?php echo esc_html( SC_EI_Support_Schema::label( SC_EI_Support_Schema::stages(), $selected['workflow_stage'] ) ); ?></span></div><dl class="sc-ei-details-grid"><dt><?php esc_html_e( 'Sender', 'sustainable-catalyst-engagement-intake' ); ?></dt><dd><?php echo esc_html( $inquiry['contact_name'] . ' · ' . $inquiry['contact_email'] ); ?></dd><dt><?php esc_html_e( 'Product', 'sustainable-catalyst-engagement-intake' ); ?></dt><dd><?php echo esc_html( SC_EI_Support_Schema::label( SC_EI_Support_Schema::products(), $selected['product'] ) . ' ' . $selected['product_version'] ); ?></dd><dt><?php esc_html_e( 'Component', 'sustainable-catalyst-engagement-intake' ); ?></dt><dd><?php echo esc_html( $selected['component'] ?: '—' ); ?></dd><dt><?php esc_html_e( 'Source', 'sustainable-catalyst-engagement-intake' ); ?></dt><dd><?php echo esc_html( $selected['source_system'] . ( $selected['source_reference'] ? ' · ' . $selected['source_reference'] : '' ) ); ?></dd></dl></section>
		<div class="sc-ei-two-column"><section class="sc-ei-panel"><h2><?php esc_html_e( 'Case context', 'sustainable-catalyst-engagement-intake' ); ?></h2><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" class="sc-ei-admin-form"><input type="hidden" name="action" value="sc_ei_support_update"><input type="hidden" name="support_case_id" value="<?php echo esc_attr( $selected['id'] ); ?>"><?php wp_nonce_field( 'sc_ei_support_update_' . absint( $selected['id'] ) ); ?>
		<label><span><?php esc_html_e( 'Product', 'sustainable-catalyst-engagement-intake' ); ?></span><select name="product"><?php foreach ( SC_EI_Support_Schema::products() as $key => $label ) : ?><option value="<?php echo esc_attr( $key ); ?>" <?php selected( $selected['product'], $key ); ?>><?php echo esc_html( $label ); ?></option><?php endforeach; ?></select></label><label><span><?php esc_html_e( 'Version', 'sustainable-catalyst-engagement-intake' ); ?></span><input name="product_version" value="<?php echo esc_attr( $selected['product_version'] ); ?>"></label><label><span><?php esc_html_e( 'Component', 'sustainable-catalyst-engagement-intake' ); ?></span><input name="component" value="<?php echo esc_attr( $selected['component'] ); ?>"></label><label><span><?php esc_html_e( 'Issue type', 'sustainable-catalyst-engagement-intake' ); ?></span><select name="issue_type"><?php foreach ( SC_EI_Support_Schema::issue_types() as $key => $label ) : ?><option value="<?php echo esc_attr( $key ); ?>" <?php selected( $selected['issue_type'], $key ); ?>><?php echo esc_html( $label ); ?></option><?php endforeach; ?></select></label><label><span><?php esc_html_e( 'Severity', 'sustainable-catalyst-engagement-intake' ); ?></span><select name="severity"><?php foreach ( SC_EI_Support_Schema::severities() as $key => $label ) : ?><option value="<?php echo esc_attr( $key ); ?>" <?php selected( $selected['severity'], $key ); ?>><?php echo esc_html( $label ); ?></option><?php endforeach; ?></select></label><label><span><?php esc_html_e( 'Priority', 'sustainable-catalyst-engagement-intake' ); ?></span><select name="priority"><?php foreach ( SC_EI_Lifecycle_Schema::priorities() as $key => $label ) : ?><option value="<?php echo esc_attr( $key ); ?>" <?php selected( $selected['priority'], $key ); ?>><?php echo esc_html( $label ); ?></option><?php endforeach; ?></select></label><label><span><?php esc_html_e( 'Assignee', 'sustainable-catalyst-engagement-intake' ); ?></span><select name="assigned_user_id"><option value="0"><?php esc_html_e( 'Unassigned', 'sustainable-catalyst-engagement-intake' ); ?></option><?php foreach ( $users as $user ) : ?><option value="<?php echo esc_attr( $user->ID ); ?>" <?php selected( $selected['assigned_user_id'], $user->ID ); ?>><?php echo esc_html( $user->display_name ); ?></option><?php endforeach; ?></select></label>
		<label><span><?php esc_html_e( 'Known issue reference', 'sustainable-catalyst-engagement-intake' ); ?></span><input name="known_issue_reference" value="<?php echo esc_attr( $selected['known_issue_reference'] ); ?>"></label><label><span><?php esc_html_e( 'Error message', 'sustainable-catalyst-engagement-intake' ); ?></span><textarea name="error_message" rows="4"><?php echo esc_textarea( $selected['error_message'] ); ?></textarea></label><label><span><?php esc_html_e( 'Reproduction steps', 'sustainable-catalyst-engagement-intake' ); ?></span><textarea name="reproduction_steps" rows="5"><?php echo esc_textarea( $selected['reproduction_steps'] ); ?></textarea></label><label><span><?php esc_html_e( 'Expected behavior', 'sustainable-catalyst-engagement-intake' ); ?></span><textarea name="expected_behavior" rows="3"><?php echo esc_textarea( $selected['expected_behavior'] ); ?></textarea></label><label><span><?php esc_html_e( 'Actual behavior', 'sustainable-catalyst-engagement-intake' ); ?></span><textarea name="actual_behavior" rows="3"><?php echo esc_textarea( $selected['actual_behavior'] ); ?></textarea></label>
		<label><span><?php esc_html_e( 'Browser', 'sustainable-catalyst-engagement-intake' ); ?></span><input name="environment_browser" value="<?php echo esc_attr( $environment['browser'] ?? '' ); ?>"></label><label><span><?php esc_html_e( 'Operating system', 'sustainable-catalyst-engagement-intake' ); ?></span><input name="environment_os" value="<?php echo esc_attr( $environment['os'] ?? '' ); ?>"></label><label><span><?php esc_html_e( 'WordPress', 'sustainable-catalyst-engagement-intake' ); ?></span><input name="environment_wordpress" value="<?php echo esc_attr( $environment['wordpress'] ?? '' ); ?>"></label><label><span><?php esc_html_e( 'PHP', 'sustainable-catalyst-engagement-intake' ); ?></span><input name="environment_php" value="<?php echo esc_attr( $environment['php'] ?? '' ); ?>"></label><label><span><?php esc_html_e( 'Product plugin version', 'sustainable-catalyst-engagement-intake' ); ?></span><input name="environment_plugin_version" value="<?php echo esc_attr( $environment['plugin_version'] ?? '' ); ?>"></label><label><span><?php esc_html_e( 'Backend version', 'sustainable-catalyst-engagement-intake' ); ?></span><input name="environment_backend_version" value="<?php echo esc_attr( $environment['backend_version'] ?? '' ); ?>"></label><label><span><?php esc_html_e( 'Affected URL', 'sustainable-catalyst-engagement-intake' ); ?></span><input type="url" name="environment_url" value="<?php echo esc_attr( $environment['url'] ?? '' ); ?>"></label>
		<label><span><?php esc_html_e( 'Sender-safe summary', 'sustainable-catalyst-engagement-intake' ); ?></span><textarea name="sender_summary" rows="4"><?php echo esc_textarea( $selected['sender_summary'] ); ?></textarea></label><label><span><?php esc_html_e( 'Sender-safe next step', 'sustainable-catalyst-engagement-intake' ); ?></span><textarea name="sender_next_step" rows="3"><?php echo esc_textarea( $selected['sender_next_step'] ); ?></textarea></label><button class="button button-primary"><?php esc_html_e( 'Update Support Case', 'sustainable-catalyst-engagement-intake' ); ?></button></form></section>
		<section class="sc-ei-panel"><h2><?php esc_html_e( 'Governed support transition', 'sustainable-catalyst-engagement-intake' ); ?></h2><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" class="sc-ei-admin-form"><input type="hidden" name="action" value="sc_ei_support_transition"><input type="hidden" name="support_case_id" value="<?php echo esc_attr( $selected['id'] ); ?>"><?php wp_nonce_field( 'sc_ei_support_transition_' . absint( $selected['id'] ) ); ?><label><span><?php esc_html_e( 'New stage', 'sustainable-catalyst-engagement-intake' ); ?></span><select name="support_stage"><?php foreach ( SC_EI_Support_Schema::allowed_transitions()[ $selected['workflow_stage'] ] ?? array() as $key ) : ?><option value="<?php echo esc_attr( $key ); ?>"><?php echo esc_html( SC_EI_Support_Schema::label( SC_EI_Support_Schema::stages(), $key ) ); ?></option><?php endforeach; ?></select></label><label><span><?php esc_html_e( 'Reason', 'sustainable-catalyst-engagement-intake' ); ?></span><textarea name="transition_reason" rows="4"></textarea></label><label><span><?php esc_html_e( 'Typed confirmation', 'sustainable-catalyst-engagement-intake' ); ?></span><input name="support_confirmation" placeholder="MOVE <?php echo esc_attr( strtoupper( $selected['case_number'] ) ); ?> TO STAGE"></label><button class="button"><?php esc_html_e( 'Change Support Stage', 'sustainable-catalyst-engagement-intake' ); ?></button></form>
		<h2><?php esc_html_e( 'Product relationship', 'sustainable-catalyst-engagement-intake' ); ?></h2><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" class="sc-ei-admin-form"><input type="hidden" name="action" value="sc_ei_support_add_link"><input type="hidden" name="support_case_id" value="<?php echo esc_attr( $selected['id'] ); ?>"><?php wp_nonce_field( 'sc_ei_support_add_link_' . absint( $selected['id'] ) ); ?><label><span><?php esc_html_e( 'Type', 'sustainable-catalyst-engagement-intake' ); ?></span><select name="related_type"><?php foreach ( SC_EI_Support_Schema::relationship_types() as $key => $label ) : ?><option value="<?php echo esc_attr( $key ); ?>"><?php echo esc_html( $label ); ?></option><?php endforeach; ?></select></label><label><span><?php esc_html_e( 'Reference', 'sustainable-catalyst-engagement-intake' ); ?></span><input name="related_reference" required></label><label><span><?php esc_html_e( 'Title', 'sustainable-catalyst-engagement-intake' ); ?></span><input name="link_title"></label><label><span><?php esc_html_e( 'URL', 'sustainable-catalyst-engagement-intake' ); ?></span><input type="url" name="link_url"></label><label class="sc-ei-check"><input type="checkbox" name="sender_visible" value="1"><span><?php esc_html_e( 'Publish this relationship to the Sender Portal', 'sustainable-catalyst-engagement-intake' ); ?></span></label><button class="button"><?php esc_html_e( 'Add Relationship', 'sustainable-catalyst-engagement-intake' ); ?></button></form>
		<h2><?php esc_html_e( 'Privacy-safe product signal', 'sustainable-catalyst-engagement-intake' ); ?></h2><form method="post" action="<?php echo esc_url( admin_url( 'admin-post.php' ) ); ?>" class="sc-ei-admin-form"><input type="hidden" name="action" value="sc_ei_support_add_signal"><input type="hidden" name="support_case_id" value="<?php echo esc_attr( $selected['id'] ); ?>"><?php wp_nonce_field( 'sc_ei_support_add_signal_' . absint( $selected['id'] ) ); ?><label><span><?php esc_html_e( 'Signal type', 'sustainable-catalyst-engagement-intake' ); ?></span><select name="signal_type"><?php foreach ( SC_EI_Support_Schema::signal_types() as $key => $label ) : ?><option value="<?php echo esc_attr( $key ); ?>"><?php echo esc_html( $label ); ?></option><?php endforeach; ?></select></label><label><span><?php esc_html_e( 'Nonpersonal summary', 'sustainable-catalyst-engagement-intake' ); ?></span><input name="signal_summary" required maxlength="255"></label><button class="button"><?php esc_html_e( 'Record Signal', 'sustainable-catalyst-engagement-intake' ); ?></button></form></section></div>
		<section class="sc-ei-panel"><h2><?php esc_html_e( 'Linked product records', 'sustainable-catalyst-engagement-intake' ); ?></h2><?php if ( ! $links ) : ?><p><?php esc_html_e( 'No knowledge articles, known issues, suggestions, releases, events, or duplicate cases are linked.', 'sustainable-catalyst-engagement-intake' ); ?></p><?php endif; ?><div class="sc-ei-timeline"><?php foreach ( $links as $link ) : ?><article><strong><?php echo esc_html( SC_EI_Support_Schema::label( SC_EI_Support_Schema::relationship_types(), $link['related_type'] ) . ': ' . ( $link['title'] ?: $link['related_reference'] ) ); ?></strong><small><?php echo $link['sender_visible'] ? esc_html__( 'Sender-visible', 'sustainable-catalyst-engagement-intake' ) : esc_html__( 'Internal only', 'sustainable-catalyst-engagement-intake' ); ?></small><?php if ( $link['url'] ) : ?><p><a href="<?php echo esc_url( $link['url'] ); ?>" target="_blank" rel="noopener noreferrer"><?php echo esc_html( $link['url'] ); ?></a></p><?php endif; ?></article><?php endforeach; ?></div></section>
		<section class="sc-ei-panel"><h2><?php esc_html_e( 'Support audit timeline', 'sustainable-catalyst-engagement-intake' ); ?></h2><div class="sc-ei-timeline"><?php foreach ( $events as $event ) : ?><article><strong><?php echo esc_html( ucwords( str_replace( '_', ' ', $event['event_type'] ) ) ); ?></strong><small><?php echo esc_html( get_date_from_gmt( $event['occurred_at'], 'M j, Y g:i a' ) ); ?></small><?php if ( $event['from_stage'] || $event['to_stage'] ) : ?><p><?php echo esc_html( ( $event['from_stage'] ?: '—' ) . ' → ' . ( $event['to_stage'] ?: '—' ) ); ?></p><?php endif; ?></article><?php endforeach; ?></div></section>
		</main><?php endif; ?>
	</div>
</div>
