<?php
/**
 * Queue-only retention candidate generation and verified execution.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

final class SC_EI_Retention_Engine {

	public static function preview( int $limit = 100 ): array {
		$candidates = self::candidates( $limit );
		return array(
			'generated_at_utc' => current_time( 'mysql', true ),
			'count'            => count( $candidates ),
			'attachment_count' => count( array_filter( $candidates, static fn( array $item ): bool => 'attachment' === $item['target_type'] ) ),
			'inquiry_count'    => count( array_filter( $candidates, static fn( array $item ): bool => 'inquiry' === $item['target_type'] ) ),
			'communication_count' => count( array_filter( $candidates, static fn( array $item ): bool => 'communication' === $item['target_type'] ) ),
			'total_bytes'      => array_sum( array_map( static fn( array $item ): int => absint( $item['size_bytes'] ?? 0 ), $candidates ) ),
			'items'            => $candidates,
		);
	}

	public static function queue_candidates( int $limit = 100, int $actor_user_id = 0, string $source = 'manual' ): array {
		$queued = 0;
		$existing = 0;
		$blocked = 0;
		$failed = 0;
		$items = array();

		foreach ( self::candidates( $limit ) as $candidate ) {
			$result = SC_EI_Privacy_Repository::queue_action(
				array(
					'inquiry_id'     => $candidate['inquiry_id'],
					'target_type'    => $candidate['target_type'],
					'target_id'      => $candidate['target_id'],
					'policy_key'     => $candidate['policy_key'],
					'policy_version' => $candidate['policy_version'],
					'action_type'    => $candidate['action_type'],
					'due_at'         => $candidate['due_at'],
					'dedupe_key'     => $candidate['dedupe_key'],
					'reason'         => sprintf(
						'Retention candidate generated by %s from policy %s v%d.',
						sanitize_key( $source ),
						$candidate['policy_key'],
						$candidate['policy_version']
					),
					'snapshot'       => $candidate,
				),
				$actor_user_id
			);
			if ( is_wp_error( $result ) ) {
				$failed++;
				$items[] = array( 'candidate' => $candidate, 'error' => $result->get_error_code() );
				continue;
			}
			if ( 'blocked_hold' === $result['status'] ) {
				$blocked++;
			} elseif ( strtotime( $result['created_at'] . ' UTC' ) < time() - 5 ) {
				$existing++;
			} else {
				$queued++;
			}
			$items[] = array( 'candidate' => $candidate, 'action_id' => absint( $result['id'] ), 'status' => $result['status'] );
		}

		$report = array(
			'completed_at_utc' => current_time( 'mysql', true ),
			'source'           => sanitize_key( $source ),
			'candidate_count'  => count( $items ),
			'queued_count'     => $queued,
			'existing_count'   => $existing,
			'blocked_count'    => $blocked,
			'failed_count'     => $failed,
			'limit'            => $limit,
		);
		update_option( 'sc_ei_last_retention_queue_run', $report, false );
		SC_EI_Audit_Log::record(
			'retention_candidates_queued',
			'Retention candidate scan completed. No physical deletion was performed.',
			$report,
			null,
			null,
			$actor_user_id ?: null
		);
		return $report;
	}

	public static function candidates( int $limit = 100 ): array {
		global $wpdb;

		$limit = max( 1, min( 1000, $limit ) );
		$remaining = $limit;
		$results = array();
		$policies = SC_EI_Retention_Policy_Repository::active();
		$now = current_time( 'mysql', true );

		foreach ( $policies as $policy ) {
			if ( $remaining <= 0 ) {
				break;
			}
			$rows = array();
			$target_type = $policy['target_type'];
			if ( 'attachment' === $target_type ) {
				$attachments = SC_EI_Database::table( 'attachments' );
				$inquiries = SC_EI_Database::table( 'inquiries' );
				$rows = (array) $wpdb->get_results(
					$wpdb->prepare(
						"SELECT a.id AS target_id, a.inquiry_id, a.original_name AS label, a.size_bytes,
							a.retention_until AS due_at, i.reference, i.contact_name
						FROM {$attachments} a
						INNER JOIN {$inquiries} i ON i.id = a.inquiry_id
						WHERE a.deleted_at IS NULL
							AND a.retention_until IS NOT NULL
							AND a.retention_until <= %s
						ORDER BY a.retention_until ASC
						LIMIT %d", // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
						$now,
						$remaining
					),
					ARRAY_A
				);
			} elseif ( 'communication' === $target_type ) {
				$communications = SC_EI_Database::table( 'communications' );
				$inquiries = SC_EI_Database::table( 'inquiries' );
				$days = max( 1, absint( $policy['retention_days'] ) );
				$cutoff = gmdate( 'Y-m-d H:i:s', time() - $days * DAY_IN_SECONDS );
				$anchor = in_array( $policy['anchor_field'], array( 'created_at', 'accepted_at', 'occurred_at' ), true )
					? $policy['anchor_field']
					: 'created_at';
				$rows = (array) $wpdb->get_results(
					$wpdb->prepare(
						"SELECT c.id AS target_id, c.inquiry_id, c.subject AS label, 0 AS size_bytes,
							COALESCE(c.{$anchor}, c.created_at) AS due_at, i.reference, i.contact_name
						FROM {$communications} c
						INNER JOIN {$inquiries} i ON i.id = c.inquiry_id
						WHERE c.deleted_at IS NULL
							AND c.body_text NOT IN ('', '[Communication content erased through Privacy and Retention Center.]')
							AND COALESCE(c.{$anchor}, c.created_at) <= %s
						ORDER BY COALESCE(c.{$anchor}, c.created_at) ASC
						LIMIT %d", // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
						$cutoff,
						$remaining
					),
					ARRAY_A
				);
			} elseif ( 'inquiry' === $target_type ) {
				$scope = array_values( array_filter( array_map( 'sanitize_key', (array) $policy['status_scope_array'] ) ) );
				if ( ! $scope ) {
					continue;
				}
				$inquiries = SC_EI_Database::table( 'inquiries' );
				$days = max( 1, absint( $policy['retention_days'] ) );
				$cutoff = gmdate( 'Y-m-d H:i:s', time() - $days * DAY_IN_SECONDS );
				$anchor = in_array( $policy['anchor_field'], array( 'created_at', 'updated_at', 'closed_at' ), true )
					? $policy['anchor_field']
					: 'created_at';
				$placeholders = implode( ',', array_fill( 0, count( $scope ), '%s' ) );
				$sql = "SELECT i.id AS target_id, i.id AS inquiry_id, i.subject AS label, 0 AS size_bytes,
						COALESCE(i.{$anchor}, i.updated_at, i.created_at) AS due_at, i.reference, i.contact_name
					FROM {$inquiries} i
					WHERE i.status IN ({$placeholders})
						AND i.privacy_status <> 'erased'
						AND COALESCE(i.{$anchor}, i.updated_at, i.created_at) <= %s
					ORDER BY COALESCE(i.{$anchor}, i.updated_at, i.created_at) ASC
					LIMIT %d";
				$rows = (array) $wpdb->get_results(
					$wpdb->prepare( $sql, array_merge( $scope, array( $cutoff, $remaining ) ) ), // phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
					ARRAY_A
				);
			}

			foreach ( $rows as $row ) {
				$target_id = absint( $row['target_id'] );
				$due_at = sanitize_text_field( (string) $row['due_at'] );
				$results[] = array(
					'inquiry_id'     => absint( $row['inquiry_id'] ),
					'target_type'    => $target_type,
					'target_id'      => $target_id,
					'label'          => sanitize_text_field( (string) $row['label'] ),
					'reference'      => sanitize_text_field( (string) $row['reference'] ),
					'contact_name'   => sanitize_text_field( (string) $row['contact_name'] ),
					'size_bytes'     => absint( $row['size_bytes'] ?? 0 ),
					'due_at'         => $due_at ?: $now,
					'policy_key'     => sanitize_key( $policy['policy_key'] ),
					'policy_version' => absint( $policy['version'] ),
					'action_type'    => sanitize_key( $policy['action_type'] ),
					'dedupe_key'     => sprintf(
						'%s:%d:%s:%d',
						$target_type,
						$target_id,
						sanitize_key( $policy['action_type'] ),
						absint( $policy['version'] )
					),
					'hold_active'    => (bool) SC_EI_Privacy_Repository::active_hold(
						absint( $row['inquiry_id'] ),
						'attachment' === $target_type ? $target_id : 0
					),
				);
				$remaining--;
				if ( $remaining <= 0 ) {
					break 2;
				}
			}
		}

		usort(
			$results,
			static fn( array $a, array $b ): int => strcmp( $a['due_at'], $b['due_at'] )
		);
		return $results;
	}

	public static function execute_action( int $action_id, int $actor_user_id ) {
		$action = SC_EI_Privacy_Repository::find_action( $action_id );
		if ( ! $action ) {
			return new WP_Error( 'retention_action_not_found', __( 'The retention action could not be found.', 'sustainable-catalyst-engagement-intake' ) );
		}
		$settings = wp_parse_args( get_option( 'sc_ei_settings', array() ), SC_EI_Privacy_Schema::default_settings() );
		$allowed_statuses = ! empty( $settings['require_retention_approval'] ) ? array( 'approved' ) : array( 'queued', 'approved' );
		if ( ! in_array( $action['status'], $allowed_statuses, true ) ) {
			return new WP_Error( 'retention_action_not_executable', __( 'The retention action is not approved for execution.', 'sustainable-catalyst-engagement-intake' ) );
		}
		$hold = SC_EI_Privacy_Repository::active_hold(
			absint( $action['inquiry_id'] ),
			'attachment' === $action['target_type'] ? absint( $action['target_id'] ) : 0
		);
		if ( $hold ) {
			SC_EI_Privacy_Repository::update_action(
				$action_id,
				array(
					'status' => 'blocked_hold',
					'failure_code' => 'legal_hold_active',
					'failure_message' => sanitize_textarea_field( $hold['reason'] ),
					'action_version' => absint( $action['action_version'] ) + 1,
				),
				array( 'action_version' )
			);
			return new WP_Error( 'legal_hold_active', __( 'An active legal hold blocks this action.', 'sustainable-catalyst-engagement-intake' ) );
		}
		if ( ! SC_EI_Privacy_Repository::update_action(
			$action_id,
			array(
				'status' => 'executing',
				'executed_by' => $actor_user_id,
				'executed_at' => current_time( 'mysql', true ),
				'failure_code' => '',
				'failure_message' => '',
				'action_version' => absint( $action['action_version'] ) + 1,
			),
			array( 'executed_by', 'action_version' )
		) ) {
			return new WP_Error( 'retention_action_lock_failed', __( 'The retention action could not enter execution state.', 'sustainable-catalyst-engagement-intake' ) );
		}

		try {
			$result = match ( $action['action_type'] ) {
				'delete_attachment'    => self::execute_attachment( $action, $actor_user_id ),
				'redact_communication' => self::execute_communication( $action, $actor_user_id ),
				'redact_inquiry'       => self::execute_inquiry( $action, $actor_user_id ),
				'archive_only'         => self::execute_archive( $action, $actor_user_id ),
				default                => new WP_Error( 'retention_action_unknown', __( 'The retention action type is unsupported.', 'sustainable-catalyst-engagement-intake' ) ),
			};
		} catch ( Throwable $exception ) {
			$result = new WP_Error( 'retention_execution_exception', $exception->getMessage() );
		}

		if ( is_wp_error( $result ) ) {
			SC_EI_Privacy_Repository::update_action(
				$action_id,
				array(
					'status' => 'failed',
					'failure_code' => sanitize_key( $result->get_error_code() ),
					'failure_message' => sanitize_textarea_field( $result->get_error_message() ),
					'action_version' => absint( $action['action_version'] ) + 2,
				),
				array( 'action_version' )
			);
			SC_EI_Audit_Log::record(
				'retention_action_failed',
				'Retention action failed and requires review.',
				array( 'action_id' => $action_id, 'error_code' => $result->get_error_code(), 'action_type' => $action['action_type'] ),
				absint( $action['inquiry_id'] ),
				'attachment' === $action['target_type'] ? absint( $action['target_id'] ) : null,
				$actor_user_id
			);
			return $result;
		}

		$verified_at = current_time( 'mysql', true );
		SC_EI_Privacy_Repository::update_action(
			$action_id,
			array(
				'status' => 'executed',
				'verified_at' => $verified_at,
				'failure_code' => '',
				'failure_message' => '',
				'action_version' => absint( $action['action_version'] ) + 2,
				'snapshot_json' => wp_json_encode(
					array(
						'privacy_schema_version' => SC_EI_PRIVACY_SCHEMA_VERSION,
						'result' => $result,
						'verified_at' => $verified_at,
					)
				),
			),
			array( 'action_version' )
		);
		SC_EI_Audit_Log::record(
			'retention_action_executed',
			'Retention action executed and verified.',
			array( 'action_id' => $action_id, 'action_type' => $action['action_type'], 'target_type' => $action['target_type'], 'result' => $result ),
			absint( $action['inquiry_id'] ),
			'attachment' === $action['target_type'] ? absint( $action['target_id'] ) : null,
			$actor_user_id
		);
		return SC_EI_Privacy_Repository::find_action( $action_id );
	}

	private static function execute_attachment( array $action, int $actor_user_id ) {
		$attachment = SC_EI_Attachment_Repository::find( absint( $action['target_id'] ) );
		if ( ! $attachment || absint( $attachment['inquiry_id'] ) !== absint( $action['inquiry_id'] ) ) {
			return new WP_Error( 'attachment_not_found', __( 'The private document record could not be found.', 'sustainable-catalyst-engagement-intake' ) );
		}
		if ( ! empty( $attachment['deleted_at'] ) ) {
			return array( 'already_deleted' => true, 'attachment_id' => absint( $attachment['id'] ) );
		}
		$absolute = SC_EI_Storage::absolute_path( (string) $attachment['relative_path'] );
		if ( $absolute && is_file( $absolute ) && ! SC_EI_Storage::delete_file( (string) $attachment['relative_path'] ) ) {
			return new WP_Error( 'physical_delete_failed', __( 'The private document could not be deleted from protected storage.', 'sustainable-catalyst-engagement-intake' ) );
		}
		$absolute_after = SC_EI_Storage::absolute_path( (string) $attachment['relative_path'] );
		if ( $absolute_after && is_file( $absolute_after ) ) {
			return new WP_Error( 'physical_delete_not_verified', __( 'The document still exists after the delete attempt.', 'sustainable-catalyst-engagement-intake' ) );
		}
		if ( ! SC_EI_Attachment_Repository::mark_deleted(
			absint( $attachment['id'] ),
			$actor_user_id,
			'Private document deleted through an approved Privacy and Retention Center action.',
			'deleted'
		) ) {
			return new WP_Error( 'attachment_tombstone_failed', __( 'The physical file was removed, but the database tombstone could not be recorded.', 'sustainable-catalyst-engagement-intake' ) );
		}
		return array(
			'attachment_id' => absint( $attachment['id'] ),
			'sha256'        => sanitize_text_field( (string) $attachment['sha256'] ),
			'size_bytes'    => absint( $attachment['size_bytes'] ),
			'physical_absence_verified' => true,
		);
	}

	private static function execute_communication( array $action, int $actor_user_id ) {
		global $wpdb;
		$communication = SC_EI_Communication_Repository::find( absint( $action['target_id'] ) );
		if ( ! $communication || absint( $communication['inquiry_id'] ) !== absint( $action['inquiry_id'] ) ) {
			return new WP_Error( 'communication_not_found', __( 'The communication record could not be found.', 'sustainable-catalyst-engagement-intake' ) );
		}

		$now = current_time( 'mysql', true );
		$redacted_context = wp_json_encode(
			array(
				'personal_data_erased'   => true,
				'privacy_schema_version' => SC_EI_PRIVACY_SCHEMA_VERSION,
			)
		);

		$wpdb->query( 'START TRANSACTION' ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery
		try {
			$updated = $wpdb->update(
				SC_EI_Database::table( 'communications' ),
				array(
					'subject'             => '[Personal data erased]',
					'body_text'           => '[Communication content erased through Privacy and Retention Center.]',
					'sender_name'         => '',
					'sender_email'        => '',
					'recipient_name'      => '',
					'recipient_email'     => '',
					'cc_json'             => '[]',
					'provider_message_id' => '',
					'error_message'       => '',
					'message_hash'        => '',
					'dedupe_key'          => null,
					'metadata_json'       => $redacted_context,
					'updated_at'          => $now,
				),
				array( 'id' => absint( $communication['id'] ) ),
				array( '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s' ),
				array( '%d' )
			);
			$events_updated = $wpdb->query(
				$wpdb->prepare(
					"UPDATE " . SC_EI_Database::table( 'communication_events' ) . "
					SET provider_message_id = '', error_message = '', context_json = %s
					WHERE communication_id = %d", // phpcs:ignore WordPress.DB.PreparedSQL.NotPrepared
					$redacted_context,
					absint( $communication['id'] )
				)
			);
			if ( false === $updated || false === $events_updated ) {
				throw new RuntimeException( 'Communication or delivery-event personal data could not be redacted.' );
			}
			$wpdb->query( 'COMMIT' ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery
		} catch ( Throwable $exception ) {
			$wpdb->query( 'ROLLBACK' ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery
			return new WP_Error( 'communication_redaction_failed', $exception->getMessage() );
		}

		return array(
			'communication_id' => absint( $communication['id'] ),
			'content_redacted' => true,
			'event_context_redacted' => true,
		);
	}

	private static function execute_inquiry( array $action, int $actor_user_id ) {
		global $wpdb;
		$inquiry_id = absint( $action['inquiry_id'] );
		$inquiry = SC_EI_Inquiry_Repository::find( $inquiry_id );
		if ( ! $inquiry ) {
			return new WP_Error( 'inquiry_not_found', __( 'The inquiry could not be found.', 'sustainable-catalyst-engagement-intake' ) );
		}
		$attachments = SC_EI_Attachment_Repository::for_inquiry( $inquiry_id, false );
		$active = array_filter( $attachments, static fn( array $attachment ): bool => empty( $attachment['deleted_at'] ) );
		if ( $active ) {
			return new WP_Error(
				'attachments_remaining',
				sprintf(
					__( '%d private document(s) remain. Queue and verify document deletion before erasing the inquiry.', 'sustainable-catalyst-engagement-intake' ),
					count( $active )
				)
			);
		}

		$now = current_time( 'mysql', true );
		$wpdb->query( 'START TRANSACTION' ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery
		try {
			$communication_result = $wpdb->query(
				$wpdb->prepare(
					"UPDATE " . SC_EI_Database::table( 'communications' ) . "
					SET subject = %s, body_text = %s, sender_name = '', sender_email = '',
						recipient_name = '', recipient_email = '', cc_json = '[]',
						provider_message_id = '', error_message = '', message_hash = '',
						dedupe_key = NULL, metadata_json = %s, updated_at = %s
					WHERE inquiry_id = %d", // phpcs:ignore WordPress.DB.PreparedSQL.NotPrepared
					'[Personal data erased]',
					'[Communication content erased through Privacy and Retention Center.]',
					wp_json_encode( array( 'personal_data_erased' => true, 'privacy_schema_version' => SC_EI_PRIVACY_SCHEMA_VERSION ) ),
					$now,
					$inquiry_id
				)
			);
			$event_result = $wpdb->query(
				$wpdb->prepare(
					"UPDATE " . SC_EI_Database::table( 'communication_events' ) . "
					SET provider_message_id = '', error_message = '', context_json = %s
					WHERE inquiry_id = %d", // phpcs:ignore WordPress.DB.PreparedSQL.NotPrepared
					wp_json_encode( array( 'personal_data_erased' => true, 'privacy_schema_version' => SC_EI_PRIVACY_SCHEMA_VERSION ) ),
					$inquiry_id
				)
			);
			$review_result = $wpdb->query(
				$wpdb->prepare(
					"UPDATE " . SC_EI_Database::table( 'reviews' ) . "
					SET summary = '', rationale = '', information_gaps = '', conflict_notes = '',
						escalation_reason = '', snapshot_json = %s
					WHERE inquiry_id = %d", // phpcs:ignore WordPress.DB.PreparedSQL.NotPrepared
					wp_json_encode( array( 'personal_data_erased' => true, 'privacy_schema_version' => SC_EI_PRIVACY_SCHEMA_VERSION ) ),
					$inquiry_id
				)
			);
			$consent_result = $wpdb->query(
				$wpdb->prepare(
					"UPDATE " . SC_EI_Database::table( 'consent_events' ) . "
					SET evidence_text = '', subject_email_hash = ''
					WHERE inquiry_id = %d", // phpcs:ignore WordPress.DB.PreparedSQL.NotPrepared
					$inquiry_id
				)
			);
			$request_result = $wpdb->query(
				$wpdb->prepare(
					"UPDATE " . SC_EI_Database::table( 'privacy_requests' ) . "
					SET requester_name = '', requester_email = '', request_summary = '',
						resolution_summary = %s, evidence_json = %s,
						status = CASE WHEN request_type = 'erasure' AND status NOT IN ('denied','withdrawn') THEN 'completed' ELSE status END,
						completed_at = CASE WHEN request_type = 'erasure' AND completed_at IS NULL THEN %s ELSE completed_at END,
						updated_at = %s
					WHERE inquiry_id = %d", // phpcs:ignore WordPress.DB.PreparedSQL.NotPrepared
					'Personal data erased through an approved Privacy and Retention Center action.',
					wp_json_encode( array( 'personal_data_erased' => true, 'privacy_schema_version' => SC_EI_PRIVACY_SCHEMA_VERSION ) ),
					$now,
					$now,
					$inquiry_id
				)
			);
			$hold_result = $wpdb->query(
				$wpdb->prepare(
					"UPDATE " . SC_EI_Database::table( 'legal_holds' ) . "
					SET reason = '', authority = '', release_reason = '', metadata_json = %s, updated_at = %s
					WHERE inquiry_id = %d", // phpcs:ignore WordPress.DB.PreparedSQL.NotPrepared
					wp_json_encode( array( 'personal_data_erased' => true, 'privacy_schema_version' => SC_EI_PRIVACY_SCHEMA_VERSION ) ),
					$now,
					$inquiry_id
				)
			);
			$retention_result = $wpdb->query(
				$wpdb->prepare(
					"UPDATE " . SC_EI_Database::table( 'retention_actions' ) . "
					SET reason = '', failure_message = '', snapshot_json = %s, updated_at = %s
					WHERE inquiry_id = %d", // phpcs:ignore WordPress.DB.PreparedSQL.NotPrepared
					wp_json_encode( array( 'personal_data_erased' => true, 'privacy_schema_version' => SC_EI_PRIVACY_SCHEMA_VERSION ) ),
					$now,
					$inquiry_id
				)
			);
			$fit_result = SC_EI_Fit_Repository::redact_for_privacy( $inquiry_id, $now );
			$portal_result = SC_EI_Portal_Repository::redact_for_privacy( $inquiry_id, $now );
			$workflow_result = SC_EI_Workflow_Repository::redact_for_privacy( $inquiry_id, $now );
			if (
				false === $communication_result
				|| false === $event_result
				|| false === $review_result
				|| false === $consent_result
				|| false === $request_result
				|| false === $hold_result
				|| false === $retention_result
				|| false === $fit_result
				|| false === $portal_result
				|| false === $workflow_result
			) {
				throw new RuntimeException( 'Related communication, review, fit assessment, sender portal, consent, request, hold, or lifecycle data could not be redacted.' );
			}

			$data = array(
				'contact_name' => '',
				'contact_email' => 'deleted+' . $inquiry_id . '@example.invalid',
				'organization' => '',
				'role_title' => '',
				'subject' => '[Personal data erased]',
				'message' => '[Personal data erased through Privacy and Retention Center.]',
				'project_summary' => '',
				'desired_outcome' => '',
				'desired_start_date' => null,
				'deadline_date' => null,
				'preferred_contact_method' => '',
				'teams_email' => '',
				'phone_number' => '',
				'timezone' => '',
				'city' => '',
				'country' => '',
				'preferred_weekdays' => '[]',
				'preferred_time_windows' => '',
				'participant_emails' => '[]',
				'participant_count' => 0,
				'accessibility_needs' => '',
				'scheduling_notes' => '',
				'teams_meeting_url' => '',
				'scheduled_start_utc' => null,
				'scheduled_end_utc' => null,
				'scheduled_timezone' => '',
				'calendar_event_id' => '',
				'meeting_request' => '',
				'preferred_duration' => 0,
				'relevant_links' => '[]',
				'metadata_json' => wp_json_encode( array( 'personal_data_erased' => true, 'privacy_schema_version' => SC_EI_PRIVACY_SCHEMA_VERSION ) ),
				'review_summary' => '',
				'decision_rationale' => '',
				'information_gaps' => '',
				'conflict_notes' => '',
				'escalation_reason' => '',
				'do_not_email_reason' => '',
				'privacy_status' => 'erased',
				'privacy_restriction_reason' => 'Approved retention or erasure action executed.',
				'last_privacy_review_at' => $now,
				'last_privacy_review_by' => $actor_user_id,
				'personal_data_erased_at' => $now,
				'privacy_version' => absint( $inquiry['privacy_version'] ) + 1,
				'fit_assessment_status' => 'finalized' === (string) $inquiry['fit_assessment_status'] ? 'finalized' : 'not_started',
				'updated_at' => $now,
			);
			$integer = array( 'participant_count', 'preferred_duration', 'last_privacy_review_by', 'privacy_version' );
			$updated = $wpdb->update(
				SC_EI_Database::table( 'inquiries' ),
				$data,
				array( 'id' => $inquiry_id ),
				array_map( static fn( string $key ): string => in_array( $key, $integer, true ) ? '%d' : '%s', array_keys( $data ) ),
				array( '%d' )
			);
			if ( false === $updated ) {
				throw new RuntimeException( 'Inquiry personal data could not be redacted.' );
			}
			$wpdb->query( 'COMMIT' ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery
		} catch ( Throwable $exception ) {
			$wpdb->query( 'ROLLBACK' ); // phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery
			return new WP_Error( 'inquiry_redaction_failed', $exception->getMessage() );
		}

		return array(
			'inquiry_id' => $inquiry_id,
			'reference_preserved' => sanitize_text_field( (string) $inquiry['reference'] ),
			'personal_data_erased' => true,
			'tombstone_preserved' => true,
		);
	}

	private static function execute_archive( array $action, int $actor_user_id ) {
		if ( ! SC_EI_Privacy_Repository::set_inquiry_privacy_state(
			absint( $action['inquiry_id'] ),
			'archived',
			'Approved retention action archived the inquiry without personal-data erasure.',
			$actor_user_id
		) ) {
			return new WP_Error( 'archive_state_failed', __( 'The inquiry could not be moved to archived privacy state.', 'sustainable-catalyst-engagement-intake' ) );
		}
		return array( 'inquiry_id' => absint( $action['inquiry_id'] ), 'archived' => true, 'erased' => false );
	}
}
