<?php
/** Secure client workspace administration. */
if ( ! defined( 'ABSPATH' ) ) { exit; }
final class SC_EI_Workspace_Admin {
	public static function register(): void {
		foreach(array(
			'sc_ei_create_client_workspace'=>'handle_create','sc_ei_transition_client_workspace'=>'handle_transition','sc_ei_update_client_workspace'=>'handle_update',
			'sc_ei_add_workspace_milestone'=>'handle_milestone','sc_ei_add_workspace_deliverable'=>'handle_deliverable','sc_ei_publish_workspace_deliverable'=>'handle_publish_deliverable',
			'sc_ei_add_workspace_message'=>'handle_message','sc_ei_link_workspace_document'=>'handle_document'
		) as $action=>$method){add_action('admin_post_'.$action,array(__CLASS__,$method));}
	}
	public static function submenu(): void { add_submenu_page('sc-engagement-intake',__('Secure Client Workspace','sustainable-catalyst-engagement-intake'),__('Client Workspace','sustainable-catalyst-engagement-intake'),'sc_intake_view_client_workspaces','sc-engagement-intake-client-workspaces',array(__CLASS__,'page')); }
	public static function page(): void { if(!current_user_can('sc_intake_view_client_workspaces'))wp_die(esc_html__('You do not have permission to view client workspaces.','sustainable-catalyst-engagement-intake')); $workspace_id=absint($_GET['workspace_id']??0); $engagement_id=absint($_GET['engagement_id']??0); $workspaces=SC_EI_Workspace_Repository::all(200); $workspace=$workspace_id?SC_EI_Workspace_Repository::find($workspace_id):null; $engagement=$engagement_id?SC_EI_Engagement_Repository::find($engagement_id):null; $engagements=SC_EI_Engagement_Repository::all(array('per_page'=>200))['items']??array(); $members=$workspace?SC_EI_Workspace_Repository::members($workspace_id):array(); $milestones=$workspace?SC_EI_Workspace_Repository::milestones($workspace_id):array(); $deliverables=$workspace?SC_EI_Workspace_Repository::deliverables($workspace_id):array(); $messages=$workspace?SC_EI_Workspace_Repository::messages($workspace_id):array(); $documents=$workspace?SC_EI_Workspace_Repository::documents($workspace_id):array(); $events=$workspace?SC_EI_Workspace_Repository::events($workspace_id):array(); include SC_EI_DIR.'admin/views/client-workspace.php'; }
	private static function require_cap(string $cap):void{if(!current_user_can($cap))wp_die(esc_html__('Permission denied.','sustainable-catalyst-engagement-intake'));}
	private static function back(int $workspace_id=0,string $result='',string $error=''):void{$args=array('page'=>'sc-engagement-intake-client-workspaces');if($workspace_id)$args['workspace_id']=$workspace_id;if($result)$args['sc_ei_result']=$result;if($error)$args['sc_ei_error']=$error;wp_safe_redirect(add_query_arg($args,admin_url('admin.php')),303);exit;}
	public static function handle_create():void{self::require_cap('sc_intake_manage_client_workspaces');check_admin_referer('sc_ei_create_client_workspace');$r=SC_EI_Workspace_Repository::create_for_engagement(absint($_POST['engagement_id']??0),array('title'=>wp_unslash($_POST['title']??''),'owner_user_id'=>absint($_POST['owner_user_id']??0),'sender_summary'=>wp_unslash($_POST['sender_summary']??''),'sender_next_step'=>wp_unslash($_POST['sender_next_step']??''),'sender_visible'=>!empty($_POST['sender_visible'])),get_current_user_id());self::back(is_wp_error($r)?0:absint($r['id']),is_wp_error($r)?'':'workspace_created',is_wp_error($r)?$r->get_error_code():'');}
	public static function handle_transition():void{self::require_cap('sc_intake_manage_client_workspaces');$id=absint($_POST['workspace_id']??0);check_admin_referer('sc_ei_transition_client_workspace_'.$id);$r=SC_EI_Workspace_Repository::transition($id,(string)wp_unslash($_POST['status']??''),(string)wp_unslash($_POST['confirmation']??''),(string)wp_unslash($_POST['note']??''),get_current_user_id());self::back($id,is_wp_error($r)?'':'workspace_transitioned',is_wp_error($r)?$r->get_error_code():'');}
	public static function handle_update():void{self::require_cap('sc_intake_manage_client_workspaces');$id=absint($_POST['workspace_id']??0);check_admin_referer('sc_ei_update_client_workspace_'.$id);$r=SC_EI_Workspace_Repository::update_sender_projection($id,array('sender_summary'=>wp_unslash($_POST['sender_summary']??''),'sender_next_step'=>wp_unslash($_POST['sender_next_step']??''),'sender_visible'=>!empty($_POST['sender_visible'])),get_current_user_id());self::back($id,is_wp_error($r)?'':'workspace_updated',is_wp_error($r)?$r->get_error_code():'');}
	public static function handle_milestone():void{self::require_cap('sc_intake_manage_workspace_milestones');$id=absint($_POST['workspace_id']??0);check_admin_referer('sc_ei_add_workspace_milestone_'.$id);$r=SC_EI_Workspace_Repository::add_milestone($id,array('title'=>wp_unslash($_POST['title']??''),'description'=>wp_unslash($_POST['description']??''),'status'=>wp_unslash($_POST['status']??'planned'),'due_date'=>wp_unslash($_POST['due_date']??''),'sender_visible'=>!empty($_POST['sender_visible']),'sort_order'=>absint($_POST['sort_order']??0)),get_current_user_id());self::back($id,is_wp_error($r)?'':'milestone_added',is_wp_error($r)?$r->get_error_code():'');}
	public static function handle_deliverable():void{self::require_cap('sc_intake_manage_workspace_deliverables');$id=absint($_POST['workspace_id']??0);check_admin_referer('sc_ei_add_workspace_deliverable_'.$id);$r=SC_EI_Workspace_Repository::add_deliverable($id,array('title'=>wp_unslash($_POST['title']??''),'description'=>wp_unslash($_POST['description']??''),'due_date'=>wp_unslash($_POST['due_date']??''),'sender_visible'=>!empty($_POST['sender_visible']),'approval_required'=>!empty($_POST['approval_required']),'attachment_id'=>absint($_POST['attachment_id']??0)),get_current_user_id());self::back($id,is_wp_error($r)?'':'deliverable_added',is_wp_error($r)?$r->get_error_code():'');}
	public static function handle_publish_deliverable():void{self::require_cap('sc_intake_manage_workspace_deliverables');$id=absint($_POST['deliverable_id']??0);$wid=absint($_POST['workspace_id']??0);check_admin_referer('sc_ei_publish_workspace_deliverable_'.$id);$r=SC_EI_Workspace_Repository::publish_deliverable($id,!empty($_POST['sender_visible']),get_current_user_id());self::back($wid,is_wp_error($r)?'':'deliverable_published',is_wp_error($r)?$r->get_error_code():'');}
	public static function handle_message():void{self::require_cap('sc_intake_manage_client_workspaces');$id=absint($_POST['workspace_id']??0);check_admin_referer('sc_ei_add_workspace_message_'.$id);$r=SC_EI_Workspace_Repository::add_message($id,(string)wp_unslash($_POST['body_text']??''),!empty($_POST['sender_visible']),get_current_user_id(),absint($_POST['related_deliverable_id']??0));self::back($id,is_wp_error($r)?'':'workspace_message_added',is_wp_error($r)?$r->get_error_code():'');}
	public static function handle_document():void{self::require_cap('sc_intake_manage_workspace_documents');$id=absint($_POST['workspace_id']??0);check_admin_referer('sc_ei_link_workspace_document_'.$id);$r=SC_EI_Workspace_Repository::link_document($id,absint($_POST['attachment_id']??0),array('title'=>wp_unslash($_POST['title']??''),'version_label'=>wp_unslash($_POST['version_label']??''),'document_role'=>wp_unslash($_POST['document_role']??''),'sender_visible'=>!empty($_POST['sender_visible']),'related_deliverable_id'=>absint($_POST['related_deliverable_id']??0)),get_current_user_id());self::back($id,is_wp_error($r)?'':'workspace_document_linked',is_wp_error($r)?$r->get_error_code():'');}
}
