<?php
if ( ! defined( 'ABSPATH' ) ) { exit; }
final class SC_EI_Analytics_Admin {
 public static function register(): void { add_action('admin_post_sc_ei_analytics_snapshot',array(__CLASS__,'snapshot'));add_action('admin_post_sc_ei_analytics_export',array(__CLASS__,'export')); }
 public static function submenu(): void { add_submenu_page('sc-engagement-intake','Engagement Analytics and Service Intelligence','Analytics & Intelligence','sc_intake_view_analytics','sc-engagement-intake-analytics',array('SC_EI_Service_Intelligence_Admin','page')); }
 public static function page(): void { if(!current_user_can('sc_intake_view_analytics'))wp_die('Forbidden');$days=SC_EI_Analytics_Schema::sanitize_days($_GET['days']??SC_EI_Analytics_Repository::settings()['analytics_default_days']);$analytics=SC_EI_Analytics_Repository::dashboard($days);$snapshots=SC_EI_Analytics_Repository::snapshots(20);include SC_EI_DIR.'admin/views/analytics.php'; }
 public static function snapshot(): void { if(!current_user_can('sc_intake_manage_analytics'))wp_die('Forbidden');check_admin_referer('sc_ei_analytics_snapshot');$days=SC_EI_Analytics_Schema::sanitize_days($_POST['days']??90);$confirm=strtoupper(trim(sanitize_text_field(wp_unslash($_POST['confirmation']??''))));if(!hash_equals('SNAPSHOT ANALYTICS',$confirm)){self::go($days,'confirmation_failed');}$r=SC_EI_Analytics_Repository::create_snapshot($days,get_current_user_id());self::go($days,is_wp_error($r)?$r->get_error_code():'snapshot_created'); }
 public static function export(): void { if(!current_user_can('sc_intake_export_analytics'))wp_die('Forbidden');$days=SC_EI_Analytics_Schema::sanitize_days($_GET['days']??90);check_admin_referer('sc_ei_analytics_export_'.$days);$payload=SC_EI_Analytics_Repository::dashboard($days);SC_EI_Audit_Log::record('analytics_exported','Authorized user exported aggregate operational analytics.',array('range_days'=>$days,'personal_data'=>false),null,null,get_current_user_id());nocache_headers();header('Content-Type: application/json; charset=utf-8');header('Content-Disposition: attachment; filename="engagement-intake-analytics-'.$days.'d-'.gmdate('Ymd-His').'.json"');echo wp_json_encode($payload,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES);exit; }
 private static function go(int $days,string $msg): void { wp_safe_redirect(add_query_arg(array('page'=>'sc-engagement-intake-analytics','days'=>$days,'sc_ei_msg'=>$msg),admin_url('admin.php')),303);exit; }
}
